In [2]:
import pandas as pd
import numpy as np
import yfinance as yf
import requests
from io import StringIO
import os
from datetime import datetime, timedelta
import logging

In [9]:
import warnings

# Ignore all warnings
warnings.filterwarnings('ignore')

In [3]:
# Load CSV file
stock_data = pd.read_csv('stock_data.csv')

# Show the first few rows
print(stock_data.head())

# Show all column names
print(stock_data.columns.tolist())

         Date    A.close     A.open  AAPL.close  AAPL.open  ABBV.close  \
0  22/03/2010  21.563597  21.269431    6.763536   6.634736         NaN
1  23/03/2010  21.813002  21.601970    6.872173   6.790318         NaN
2  24/03/2010  21.678694  21.729854    6.902567   6.850505         NaN
3  25/03/2010  22.094370  21.806600    6.820715   6.949215         NaN
4  26/03/2010  21.940891  22.158317    6.948610   6.889927         NaN

   ABBV.open  ABNB.close  ABNB.open  ABT.close  ...  XYL.close  XYL.open  \
0        NaN         NaN        NaN  18.598389  ...        NaN       NaN
1        NaN         NaN        NaN  18.760651  ...        NaN       NaN
2        NaN         NaN        NaN  18.598389  ...        NaN       NaN
3        NaN         NaN        NaN  18.477552  ...        NaN       NaN
4        NaN         NaN        NaN  18.263506  ...        NaN       NaN

   YUM.close   YUM.open  ZBH.close   ZBH.open  ZBRA.close  ZBRA.open  \
0  20.547918  20.354020  50.652508  49.616831   30.129999  29.469999
1  20.601774  20.644863  50.878799  50.713438   29.950001  30.070000
2  20.424036  20.617935  50.521961  50.643808   29.410000  29.750000
3  20.494057  20.569462  50.025883  50.783061   29.030001  29.660000
4  20.612547  20.558685  49.877941  50.217364   29.320000  29.160000

   ZTS.close  ZTS.open
0        NaN       NaN
1        NaN       NaN
2        NaN       NaN
3        NaN       NaN
4        NaN       NaN

[5 rows x 1007 columns]
['Date', 'A.close', 'A.open', 'AAPL.close', 'AAPL.open', 'ABBV.close', 'ABBV.open', 'ABNB.close', 'ABNB.open', 'ABT.close', 'ABT.open', 'ACGL.close', 'ACGL.open', 'ACN.close', 'ACN.open', 'ADBE.close', 'ADBE.open', 'ADI.close', 'ADI.open', 'ADM.close', 'ADM.open', 'ADP.close', 'ADP.open', 'ADSK.close', 'ADSK.open', 'AEE.close', 'AEE.open', 'AEP.close', 'AEP.open', 'AES.close', 'AES.open', 'AFL.close', 'AFL.open', 'AIG.close', 'AIG.open', 'AIZ.close', 'AIZ.open', 'AJG.close', 'AJG.open', 'AKAM.close', 'AKAM.open', 'ALB.close', 'ALB.open', 'ALGN.close', 'ALGN.open', 'ALL.close', 'ALL.open', 'ALLE.close', 'ALLE.open', 'AMAT.close', 'AMAT.open', 'AMCR.close', 'AMCR.open', 'AMD.close', 'AMD.open', 'AME.close', 'AME.open', 'AMGN.close', 'AMGN.open', 'AMP.close', 'AMP.open', 'AMT.close', 'AMT.open', 'AMZN.close', 'AMZN.open', 'ANET.close', 'ANET.open', 'ANSS.close', 'ANSS.open', 'AON.close', 'AON.open', 'AOS.close', 'AOS.open', 'APA.close', 'APA.open', 'APD.close', 'APD.open', 'APH.close', 'APH.open', 'APO.close', 'APO.open', 'APTV.close', 'APTV.open', 'ARE.close', 'ARE.open', 'ATO.close', 'ATO.open', 'AVB.close', 'AVB.open', 'AVGO.close', 'AVGO.open', 'AVY.close', 'AVY.open', 'AWK.close', 'AWK.open', 'AXON.close', 'AXON.open', 'AXP.close', 'AXP.open', 'AZO.close', 'AZO.open', 'BA.close', 'BA.open', 'BAC.close', 'BAC.open', 'BALL.close', 'BALL.open', 'BAX.close', 'BAX.open', 'BBY.close', 'BBY.open', 'BDX.close', 'BDX.open', 'BEN.close', 'BEN.open', 'BF-B.close', 'BF-B.open', 'BG.close', 'BG.open', 'BIIB.close', 'BIIB.open', 'BK.close', 'BK.open', 'BKNG.close', 'BKNG.open', 'BKR.close', 'BKR.open', 'BLDR.close', 'BLDR.open', 'BLK.close', 'BLK.open', 'BMY.close', 'BMY.open', 'BR.close', 'BR.open', 'BRK-B.close', 'BRK-B.open', 'BRO.close', 'BRO.open', 'BSX.close', 'BSX.open', 'BWA.close', 'BWA.open', 'BX.close', 'BX.open', 'BXP.close', 'BXP.open', 'C.close', 'C.open', 'CAG.close', 'CAG.open', 'CAH.close', 'CAH.open', 'CARR.close', 'CARR.open', 'CAT.close', 'CAT.open', 'CB.close', 'CB.open', 'CBOE.close', 'CBOE.open', 'CBRE.close', 'CBRE.open', 'CCI.close', 'CCI.open', 'CCL.close', 'CCL.open', 'CDNS.close', 'CDNS.open', 'CDW.close', 'CDW.open', 'CE.close', 'CE.open', 'CEG.close', 'CEG.open', 'CF.close', 'CF.open', 'CFG.close', 'CFG.open', 'CHD.close', 'CHD.open', 'CHRW.close', 'CHRW.open', 'CHTR.close', 'CHTR.open', 'CI.close', 'CI.open', 'CINF.close', 'CINF.open', 'CL.close', 'CL.open', 'CLX.close', 'CLX.open', 'CMCSA.close', 'CMCSA.open', 'CME.close', 'CME.open', 'CMG.close', 'CMG.open', 'CMI.close', 'CMI.open', 'CMS.close', 'CMS.open', 'CNC.close', 'CNC.open', 'CNP.close', 'CNP.open', 'COF.close', 'COF.open', 'COO.close', 'COO.open', 'COP.close', 'COP.open', 'COR.close', 'COR.open', 'COST.close', 'COST.open', 'CPAY.close', 'CPAY.open', 'CPB.close', 'CPB.open', 'CPRT.close', 'CPRT.open', 'CPT.close', 'CPT.open', 'CRL.close', 'CRL.open', 'CRM.close', 'CRM.open', 'CRWD.close', 'CRWD.open', 'CSCO.close', 'CSCO.open', 'CSGP.close', 'CSGP.open', 'CSX.close', 'CSX.open', 'CTAS.close', 'CTAS.open', 'CTRA.close', 'CTRA.open', 'CTSH.close', 'CTSH.open', 'CTVA.close', 'CTVA.open', 'CVS.close', 'CVS.open', 'CVX.close', 'CVX.open', 'CZR.close', 'CZR.open', 'D.close', 'D.open', 'DAL.close', 'DAL.open', 'DAY.close', 'DAY.open', 'DD.close', 'DD.open', 'DE.close', 'DE.open', 'DECK.close', 'DECK.open', 'DELL.close', 'DELL.open', 'DFS.close', 'DFS.open', 'DG.close', 'DG.open', 'DGX.close', 'DGX.open', 'DHI.close', 'DHI.open', 'DHR.close', 'DHR.open', 'DIS.close', 'DIS.open', 'DLR.close', 'DLR.open', 'DLTR.close', 'DLTR.open', 'DOC.close', 'DOC.open', 'DOV.close', 'DOV.open', 'DOW.close', 'DOW.open', 'DPZ.close', 'DPZ.open', 'DRI.close', 'DRI.open', 'DTE.close', 'DTE.open', 'DUK.close', 'DUK.open', 'DVA.close', 'DVA.open', 'DVN.close', 'DVN.open', 'DXCM.close', 'DXCM.open', 'EA.close', 'EA.open', 'EBAY.close', 'EBAY.open', 'ECL.close', 'ECL.open', 'ED.close', 'ED.open', 'EFX.close', 'EFX.open', 'EG.close', 'EG.open', 'EIX.close', 'EIX.open', 'EL.close', 'EL.open', 'ELV.close', 'ELV.open', 'EMN.close', 'EMN.open', 'EMR.close', 'EMR.open', 'ENPH.close', 'ENPH.open', 'EOG.close', 'EOG.open', 'EPAM.close', 'EPAM.open', 'EQIX.close', 'EQIX.open', 'EQR.close', 'EQR.open', 'EQT.close', 'EQT.open', 'ERIE.close', 'ERIE.open', 'ES.close', 'ES.open', 'ESS.close', 'ESS.open', 'ETN.close', 'ETN.open', 'ETR.close', 'ETR.open', 'EVRG.close', 'EVRG.open', 'EW.close', 'EW.open', 'EXC.close', 'EXC.open', 'EXPD.close', 'EXPD.open', 'EXPE.close', 'EXPE.open', 'EXR.close', 'EXR.open', 'F.close', 'F.open', 'FANG.close', 'FANG.open', 'FAST.close', 'FAST.open', 'FCX.close', 'FCX.open', 'FDS.close', 'FDS.open', 'FDX.close', 'FDX.open', 'FE.close', 'FE.open', 'FFIV.close', 'FFIV.open', 'FI.close', 'FI.open', 'FICO.close', 'FICO.open', 'FIS.close', 'FIS.open', 'FITB.close', 'FITB.open', 'FMC.close', 'FMC.open', 'FOX.close', 'FOX.open', 'FOXA.close', 'FOXA.open', 'FRT.close', 'FRT.open', 'FSLR.close', 'FSLR.open', 'FTNT.close', 'FTNT.open', 'FTV.close', 'FTV.open', 'GD.close', 'GD.open', 'GDDY.close', 'GDDY.open', 'GE.close', 'GE.open', 'GEHC.close', 'GEHC.open', 'GEN.close', 'GEN.open', 'GEV.close', 'GEV.open', 'GILD.close', 'GILD.open', 'GIS.close', 'GIS.open', 'GL.close', 'GL.open', 'GLW.close', 'GLW.open', 'GM.close', 'GM.open', 'GNRC.close', 'GNRC.open', 'GOOG.close', 'GOOG.open', 'GOOGL.close', 'GOOGL.open', 'GPC.close', 'GPC.open', 'GPN.close', 'GPN.open', 'GRMN.close', 'GRMN.open', 'GS.close', 'GS.open', 'GWW.close', 'GWW.open', 'HAL.close', 'HAL.open', 'HAS.close', 'HAS.open', 'HBAN.close', 'HBAN.open', 'HCA.close', 'HCA.open', 'HD.close', 'HD.open', 'HES.close', 'HES.open', 'HIG.close', 'HIG.open', 'HII.close', 'HII.open', 'HLT.close', 'HLT.open', 'HOLX.close', 'HOLX.open', 'HON.close', 'HON.open', 'HPE.close', 'HPE.open', 'HPQ.close', 'HPQ.open', 'HRL.close', 'HRL.open', 'HSIC.close', 'HSIC.open', 'HST.close', 'HST.open', 'HSY.close', 'HSY.open', 'HUBB.close', 'HUBB.open', 'HUM.close', 'HUM.open', 'HWM.close', 'HWM.open', 'IBM.close', 'IBM.open', 'ICE.close', 'ICE.open', 'IDXX.close', 'IDXX.open', 'IEX.close', 'IEX.open', 'IFF.close', 'IFF.open', 'INCY.close', 'INCY.open', 'INTC.close', 'INTC.open', 'INTU.close', 'INTU.open', 'INVH.close', 'INVH.open', 'IP.close', 'IP.open', 'IPG.close', 'IPG.open', 'IQV.close', 'IQV.open', 'IR.close', 'IR.open', 'IRM.close', 'IRM.open', 'ISRG.close', 'ISRG.open', 'IT.close', 'IT.open', 'ITW.close', 'ITW.open', 'IVZ.close', 'IVZ.open', 'J.close', 'J.open', 'JBHT.close', 'JBHT.open', 'JBL.close', 'JBL.open', 'JCI.close', 'JCI.open', 'JKHY.close', 'JKHY.open', 'JNJ.close', 'JNJ.open', 'JNPR.close', 'JNPR.open', 'JPM.close', 'JPM.open', 'K.close', 'K.open', 'KDP.close', 'KDP.open', 'KEY.close', 'KEY.open', 'KEYS.close', 'KEYS.open', 'KHC.close', 'KHC.open', 'KIM.close', 'KIM.open', 'KKR.close', 'KKR.open', 'KLAC.close', 'KLAC.open', 'KMB.close', 'KMB.open', 'KMI.close', 'KMI.open', 'KMX.close', 'KMX.open', 'KO.close', 'KO.open', 'KR.close', 'KR.open', 'KVUE.close', 'KVUE.open', 'L.close', 'L.open', 'LDOS.close', 'LDOS.open', 'LEN.close', 'LEN.open', 'LH.close', 'LH.open', 'LHX.close', 'LHX.open', 'LII.close', 'LII.open', 'LIN.close', 'LIN.open', 'LKQ.close', 'LKQ.open', 'LLY.close', 'LLY.open', 'LMT.close', 'LMT.open', 'LNT.close', 'LNT.open', 'LOW.close', 'LOW.open', 'LRCX.close', 'LRCX.open', 'LULU.close', 'LULU.open', 'LUV.close', 'LUV.open', 'LVS.close', 'LVS.open', 'LW.close', 'LW.open', 'LYB.close', 'LYB.open', 'LYV.close', 'LYV.open', 'MA.close', 'MA.open', 'MAA.close', 'MAA.open', 'MAR.close', 'MAR.open', 'MAS.close', 'MAS.open', 'MCD.close', 'MCD.open', 'MCHP.close', 'MCHP.open', 'MCK.close', 'MCK.open', 'MCO.close', 'MCO.open', 'MDLZ.close', 'MDLZ.open', 'MDT.close', 'MDT.open', 'MET.close', 'MET.open', 'META.close', 'META.open', 'MGM.close', 'MGM.open', 'MHK.close', 'MHK.open', 'MKC.close', 'MKC.open', 'MKTX.close', 'MKTX.open', 'MLM.close', 'MLM.open', 'MMC.close', 'MMC.open', 'MMM.close', 'MMM.open', 'MNST.close', 'MNST.open', 'MO.close', 'MO.open', 'MOH.close', 'MOH.open', 'MOS.close', 'MOS.open', 'MPC.close', 'MPC.open', 'MPWR.close', 'MPWR.open', 'MRK.close', 'MRK.open', 'MRNA.close', 'MRNA.open', 'MS.close', 'MS.open', 'MSCI.close', 'MSCI.open', 'MSFT.close', 'MSFT.open', 'MSI.close', 'MSI.open', 'MTB.close', 'MTB.open', 'MTCH.close', 'MTCH.open', 'MTD.close', 'MTD.open', 'MU.close', 'MU.open', 'NCLH.close', 'NCLH.open', 'NDAQ.close', 'NDAQ.open', 'NDSN.close', 'NDSN.open', 'NEE.close', 'NEE.open', 'NEM.close', 'NEM.open', 'NFLX.close', 'NFLX.open', 'NI.close', 'NI.open', 'NKE.close', 'NKE.open', 'NOC.close', 'NOC.open', 'NOW.close', 'NOW.open', 'NRG.close', 'NRG.open', 'NSC.close', 'NSC.open', 'NTAP.close', 'NTAP.open', 'NTRS.close', 'NTRS.open', 'NUE.close', 'NUE.open', 'NVDA.close', 'NVDA.open', 'NVR.close', 'NVR.open', 'NWS.close', 'NWS.open', 'NWSA.close', 'NWSA.open', 'NXPI.close', 'NXPI.open', 'O.close', 'O.open', 'ODFL.close', 'ODFL.open', 'OKE.close', 'OKE.open', 'OMC.close', 'OMC.open', 'ON.close', 'ON.open', 'ORCL.close', 'ORCL.open', 'ORLY.close', 'ORLY.open', 'OTIS.close', 'OTIS.open', 'OXY.close', 'OXY.open', 'PANW.close', 'PANW.open', 'PARA.close', 'PARA.open', 'PAYC.close', 'PAYC.open', 'PAYX.close', 'PAYX.open', 'PCAR.close', 'PCAR.open', 'PCG.close', 'PCG.open', 'PEG.close', 'PEG.open', 'PEP.close', 'PEP.open', 'PFE.close', 'PFE.open', 'PFG.close', 'PFG.open', 'PG.close', 'PG.open', 'PGR.close', 'PGR.open', 'PH.close', 'PH.open', 'PHM.close', 'PHM.open', 'PKG.close', 'PKG.open', 'PLD.close', 'PLD.open', 'PLTR.close', 'PLTR.open', 'PM.close', 'PM.open', 'PNC.close', 'PNC.open', 'PNR.close', 'PNR.open', 'PNW.close', 'PNW.open', 'PODD.close', 'PODD.open', 'POOL.close', 'POOL.open', 'PPG.close', 'PPG.open', 'PPL.close', 'PPL.open', 'PRU.close', 'PRU.open', 'PSA.close', 'PSA.open', 'PSX.close', 'PSX.open', 'PTC.close', 'PTC.open', 'PWR.close', 'PWR.open', 'PYPL.close', 'PYPL.open', 'QCOM.close', 'QCOM.open', 'RCL.close', 'RCL.open', 'REG.close', 'REG.open', 'REGN.close', 'REGN.open', 'RF.close', 'RF.open', 'RJF.close', 'RJF.open', 'RL.close', 'RL.open', 'RMD.close', 'RMD.open', 'ROK.close', 'ROK.open', 'ROL.close', 'ROL.open', 'ROP.close', 'ROP.open', 'ROST.close', 'ROST.open', 'RSG.close', 'RSG.open', 'RTX.close', 'RTX.open', 'RVTY.close', 'RVTY.open', 'SBAC.close', 'SBAC.open', 'SBUX.close', 'SBUX.open', 'SCHW.close', 'SCHW.open', 'SHW.close', 'SHW.open', 'SJM.close', 'SJM.open', 'SLB.close', 'SLB.open', 'SMCI.close', 'SMCI.open', 'SNA.close', 'SNA.open', 'SNPS.close', 'SNPS.open', 'SO.close', 'SO.open', 'SOLV.close', 'SOLV.open', 'SPG.close', 'SPG.open', 'SPGI.close', 'SPGI.open', 'SRE.close', 'SRE.open', 'STE.close', 'STE.open', 'STLD.close', 'STLD.open', 'STT.close', 'STT.open', 'STX.close', 'STX.open', 'STZ.close', 'STZ.open', 'SW.close', 'SW.open', 'SWK.close', 'SWK.open', 'SWKS.close', 'SWKS.open', 'SYF.close', 'SYF.open', 'SYK.close', 'SYK.open', 'SYY.close', 'SYY.open', 'T.close', 'T.open', 'TAP.close', 'TAP.open', 'TDG.close', 'TDG.open', 'TDY.close', 'TDY.open', 'TECH.close', 'TECH.open', 'TEL.close', 'TEL.open', 'TER.close', 'TER.open', 'TFC.close', 'TFC.open', 'TFX.close', 'TFX.open', 'TGT.close', 'TGT.open', 'TJX.close', 'TJX.open', 'TMO.close', 'TMO.open', 'TMUS.close', 'TMUS.open', 'TPL.close', 'TPL.open', 'TPR.close', 'TPR.open', 'TRGP.close', 'TRGP.open', 'TRMB.close', 'TRMB.open', 'TROW.close', 'TROW.open', 'TRV.close', 'TRV.open', 'TSCO.close', 'TSCO.open', 'TSLA.close', 'TSLA.open', 'TSN.close', 'TSN.open', 'TT.close', 'TT.open', 'TTWO.close', 'TTWO.open', 'TXN.close', 'TXN.open', 'TXT.close', 'TXT.open', 'TYL.close', 'TYL.open', 'UAL.close', 'UAL.open', 'UBER.close', 'UBER.open', 'UDR.close', 'UDR.open', 'UHS.close', 'UHS.open', 'ULTA.close', 'ULTA.open', 'UNH.close', 'UNH.open', 'UNP.close', 'UNP.open', 'UPS.close', 'UPS.open', 'URI.close', 'URI.open', 'USB.close', 'USB.open', 'V.close', 'V.open', 'VICI.close', 'VICI.open', 'VLO.close', 'VLO.open', 'VLTO.close', 'VLTO.open', 'VMC.close', 'VMC.open', 'VRSK.close', 'VRSK.open', 'VRSN.close', 'VRSN.open', 'VRTX.close', 'VRTX.open', 'VST.close', 'VST.open', 'VTR.close', 'VTR.open', 'VTRS.close', 'VTRS.open', 'VZ.close', 'VZ.open', 'WAB.close', 'WAB.open', 'WAT.close', 'WAT.open', 'WBA.close', 'WBA.open', 'WBD.close', 'WBD.open', 'WDAY.close', 'WDAY.open', 'WDC.close', 'WDC.open', 'WEC.close', 'WEC.open', 'WELL.close', 'WELL.open', 'WFC.close', 'WFC.open', 'WM.close', 'WM.open', 'WMB.close', 'WMB.open', 'WMT.close', 'WMT.open', 'WRB.close', 'WRB.open', 'WST.close', 'WST.open', 'WTW.close', 'WTW.open', 'WY.close', 'WY.open', 'WYNN.close', 'WYNN.open', 'XEL.close', 'XEL.open', 'XOM.close', 'XOM.open', 'XYL.close', 'XYL.open', 'YUM.close', 'YUM.open', 'ZBH.close', 'ZBH.open', 'ZBRA.close', 'ZBRA.open', 'ZTS.close', 'ZTS.open']

In [11]:
# COMPUTING DAILY RETURNS (CLOSE TO CLOSE) --- NOTES

# df[return_col] = df[col].pct_change()
#  calculates the percentage change between the current day’s close price and the previous day’s close price for each ticker.

# Formula used
# Return_t = (Close_t / Close_t-1) - 1

In [ ]:
##  Long format


# Load your wide format data
df = pd.read_csv('stock_data.csv')
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

# Find close price columns
close_columns = [col for col in df.columns if col.endswith('.close')]

# Initialize an empty DataFrame to store the long-format data
long_df = pd.DataFrame()

# Loop through tickers to reshape and compute returns
for col in close_columns:
    ticker = col.replace('.close', '')
    
    temp_df = df[['Date', col]].copy()
    temp_df['Ticker'] = ticker
    temp_df['Return'] = temp_df[col].pct_change() 
    
    # Rename price column for clarity
    temp_df = temp_df.rename(columns={col: 'Close'})
    
    # Drop NaN returns (optional)
    temp_df = temp_df.dropna()

    # Append to long format dataframe
    long_df = pd.concat([long_df, temp_df], axis=0)

# Reorder columns
long_df = long_df[['Date', 'Ticker', 'Close', 'Return']]

# Sort by date/ticker
long_df = long_df.sort_values(['Date', 'Ticker'])

# Save to CSV
long_df.to_csv('long_format_stock_returns.csv', index=False)

print("✅ Long format file saved as long_format_stock_returns.csv")

In [10]:
# Long returns
long_returns = pd.read_csv('long_format_stock_returns.csv')
# Show the first few rows
print(long_returns.head())

# Show all column names
print(long_returns.columns.tolist())

         Date Ticker      Close    Return
0  2010-03-23      A  21.813002  0.011566
1  2010-03-23   AAPL   6.872173  0.016062
2  2010-03-23    ABT  18.760651  0.008725
3  2010-03-23   ACGL   7.951624  0.001330
4  2010-03-23    ACN  32.192348 -0.000707
['Date', 'Ticker', 'Close', 'Return']

In [ ]:
# WIDE FORMAT

df = pd.read_csv('stock_data.csv')
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

# Create new return columns next to each close price
for col in df.columns:
    if col.endswith('.close'):
        ticker = col.replace('.close', '')
        return_col = ticker + '.return'
        
        df[return_col] = df[col].pct_change()

# Save to CSV
df.to_csv('wide_format_with_returns.csv', index=False)

print("✅ Wide format file saved as wide_format_with_returns.csv")

In [6]:
wide_returns = pd.read_csv('wide_format_with_returns.csv')
# Show the first few rows
print(wide_returns.head())

# Show all column names
print(wide_returns.columns.tolist())

         Date    A.close     A.open  AAPL.close  AAPL.open  ABBV.close  \
0  2010-03-22  21.563597  21.269431    6.763536   6.634736         NaN
1  2010-03-23  21.813002  21.601970    6.872173   6.790318         NaN
2  2010-03-24  21.678694  21.729854    6.902567   6.850505         NaN
3  2010-03-25  22.094370  21.806600    6.820715   6.949215         NaN
4  2010-03-26  21.940891  22.158317    6.948610   6.889927         NaN

   ABBV.open  ABNB.close  ABNB.open  ABT.close  ...  WTW.return  WY.return  \
0        NaN         NaN        NaN  18.598389  ...         NaN        NaN
1        NaN         NaN        NaN  18.760651  ...    0.009807   0.008007
2        NaN         NaN        NaN  18.598389  ...   -0.012218  -0.007061
3        NaN         NaN        NaN  18.477552  ...    0.011100  -0.018667
4        NaN         NaN        NaN  18.263506  ...   -0.001255   0.003170

   WYNN.return  XEL.return  XOM.return  XYL.return  YUM.return  ZBH.return  \
0          NaN         NaN         NaN         NaN         NaN         NaN
1    -0.002744    0.002117   -0.000299         NaN    0.002621    0.004468
2    -0.006813   -0.010328   -0.006722         NaN   -0.008627   -0.007013
3    -0.018468   -0.000949   -0.003007         NaN    0.003428   -0.009819
4     0.029835   -0.000950    0.003620         NaN    0.005782   -0.002957

   ZBRA.return  ZTS.return
0          NaN         NaN
1    -0.005974         NaN
2    -0.018030         NaN
3    -0.012921         NaN
4     0.009990         NaN

[5 rows x 1510 columns]

In [ ]:
# RETURNS ONLY WIDE

# Load your original wide format data
df = pd.read_csv('stock_data.csv')
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

# Compute returns for each ticker's close price
for col in df.columns:
    if col.endswith('.close'):
        ticker = col.replace('.close', '')
        return_col = ticker + '.return'
        
        df[return_col] = df[col].pct_change()

# Drop all 'open' and 'close' columns, keep returns + Date
columns_to_keep = ['Date'] + [col for col in df.columns if col.endswith('.return')]
returns_only_df = df[columns_to_keep]

# Save returns-only wide format CSV
returns_only_df.to_csv('returns_only_wide_format.csv', index=False)

print("✅ Returns-only wide format file saved as returns_only_wide_format.csv")

In [14]:
#returns_only_df = pd.read_csv('returns_only_wide_format.csv')
# Show the first few rows
print(returns_only_df.head())

# Show all column names
print(returns_only_df.columns.tolist())

        Date  A.return  AAPL.return  ABBV.return  ABNB.return  ABT.return  \
0 2010-03-22       NaN          NaN          NaN          NaN         NaN
1 2010-03-23  0.011566     0.016062          NaN          NaN    0.008725
2 2010-03-24 -0.006157     0.004423          NaN          NaN   -0.008649
3 2010-03-25  0.019174    -0.011858          NaN          NaN   -0.006497
4 2010-03-26 -0.006947     0.018751          NaN          NaN   -0.011584

   ACGL.return  ACN.return  ADBE.return  ADI.return  ...  WTW.return  \
0          NaN         NaN          NaN         NaN  ...         NaN
1     0.001330   -0.000707     0.007725    0.011972  ...    0.009807
2     0.002658   -0.014387     0.036627   -0.045021  ...   -0.012218
3    -0.002650   -0.006461    -0.017529   -0.004130  ...    0.011100
4     0.000399    0.021195    -0.010036   -0.015549  ...   -0.001255

   WY.return  WYNN.return  XEL.return  XOM.return  XYL.return  YUM.return  \
0        NaN          NaN         NaN         NaN         NaN         NaN
1   0.008007    -0.002744    0.002117   -0.000299         NaN    0.002621
2  -0.007061    -0.006813   -0.010328   -0.006722         NaN   -0.008627
3  -0.018667    -0.018468   -0.000949   -0.003007         NaN    0.003428
4   0.003170     0.029835   -0.000950    0.003620         NaN    0.005782

   ZBH.return  ZBRA.return  ZTS.return
0         NaN          NaN         NaN
1    0.004468    -0.005974         NaN
2   -0.007013    -0.018030         NaN
3   -0.009819    -0.012921         NaN
4   -0.002957     0.009990         NaN

[5 rows x 504 columns]
['Date', 'A.return', 'AAPL.return', 'ABBV.return', 'ABNB.return', 'ABT.return', 'ACGL.return', 'ACN.return', 'ADBE.return', 'ADI.return', 'ADM.return', 'ADP.return', 'ADSK.return', 'AEE.return', 'AEP.return', 'AES.return', 'AFL.return', 'AIG.return', 'AIZ.return', 'AJG.return', 'AKAM.return', 'ALB.return', 'ALGN.return', 'ALL.return', 'ALLE.return', 'AMAT.return', 'AMCR.return', 'AMD.return', 'AME.return', 'AMGN.return', 'AMP.return', 'AMT.return', 'AMZN.return', 'ANET.return', 'ANSS.return', 'AON.return', 'AOS.return', 'APA.return', 'APD.return', 'APH.return', 'APO.return', 'APTV.return', 'ARE.return', 'ATO.return', 'AVB.return', 'AVGO.return', 'AVY.return', 'AWK.return', 'AXON.return', 'AXP.return', 'AZO.return', 'BA.return', 'BAC.return', 'BALL.return', 'BAX.return', 'BBY.return', 'BDX.return', 'BEN.return', 'BF-B.return', 'BG.return', 'BIIB.return', 'BK.return', 'BKNG.return', 'BKR.return', 'BLDR.return', 'BLK.return', 'BMY.return', 'BR.return', 'BRK-B.return', 'BRO.return', 'BSX.return', 'BWA.return', 'BX.return', 'BXP.return', 'C.return', 'CAG.return', 'CAH.return', 'CARR.return', 'CAT.return', 'CB.return', 'CBOE.return', 'CBRE.return', 'CCI.return', 'CCL.return', 'CDNS.return', 'CDW.return', 'CE.return', 'CEG.return', 'CF.return', 'CFG.return', 'CHD.return', 'CHRW.return', 'CHTR.return', 'CI.return', 'CINF.return', 'CL.return', 'CLX.return', 'CMCSA.return', 'CME.return', 'CMG.return', 'CMI.return', 'CMS.return', 'CNC.return', 'CNP.return', 'COF.return', 'COO.return', 'COP.return', 'COR.return', 'COST.return', 'CPAY.return', 'CPB.return', 'CPRT.return', 'CPT.return', 'CRL.return', 'CRM.return', 'CRWD.return', 'CSCO.return', 'CSGP.return', 'CSX.return', 'CTAS.return', 'CTRA.return', 'CTSH.return', 'CTVA.return', 'CVS.return', 'CVX.return', 'CZR.return', 'D.return', 'DAL.return', 'DAY.return', 'DD.return', 'DE.return', 'DECK.return', 'DELL.return', 'DFS.return', 'DG.return', 'DGX.return', 'DHI.return', 'DHR.return', 'DIS.return', 'DLR.return', 'DLTR.return', 'DOC.return', 'DOV.return', 'DOW.return', 'DPZ.return', 'DRI.return', 'DTE.return', 'DUK.return', 'DVA.return', 'DVN.return', 'DXCM.return', 'EA.return', 'EBAY.return', 'ECL.return', 'ED.return', 'EFX.return', 'EG.return', 'EIX.return', 'EL.return', 'ELV.return', 'EMN.return', 'EMR.return', 'ENPH.return', 'EOG.return', 'EPAM.return', 'EQIX.return', 'EQR.return', 'EQT.return', 'ERIE.return', 'ES.return', 'ESS.return', 'ETN.return', 'ETR.return', 'EVRG.return', 'EW.return', 'EXC.return', 'EXPD.return', 'EXPE.return', 'EXR.return', 'F.return', 'FANG.return', 'FAST.return', 'FCX.return', 'FDS.return', 'FDX.return', 'FE.return', 'FFIV.return', 'FI.return', 'FICO.return', 'FIS.return', 'FITB.return', 'FMC.return', 'FOX.return', 'FOXA.return', 'FRT.return', 'FSLR.return', 'FTNT.return', 'FTV.return', 'GD.return', 'GDDY.return', 'GE.return', 'GEHC.return', 'GEN.return', 'GEV.return', 'GILD.return', 'GIS.return', 'GL.return', 'GLW.return', 'GM.return', 'GNRC.return', 'GOOG.return', 'GOOGL.return', 'GPC.return', 'GPN.return', 'GRMN.return', 'GS.return', 'GWW.return', 'HAL.return', 'HAS.return', 'HBAN.return', 'HCA.return', 'HD.return', 'HES.return', 'HIG.return', 'HII.return', 'HLT.return', 'HOLX.return', 'HON.return', 'HPE.return', 'HPQ.return', 'HRL.return', 'HSIC.return', 'HST.return', 'HSY.return', 'HUBB.return', 'HUM.return', 'HWM.return', 'IBM.return', 'ICE.return', 'IDXX.return', 'IEX.return', 'IFF.return', 'INCY.return', 'INTC.return', 'INTU.return', 'INVH.return', 'IP.return', 'IPG.return', 'IQV.return', 'IR.return', 'IRM.return', 'ISRG.return', 'IT.return', 'ITW.return', 'IVZ.return', 'J.return', 'JBHT.return', 'JBL.return', 'JCI.return', 'JKHY.return', 'JNJ.return', 'JNPR.return', 'JPM.return', 'K.return', 'KDP.return', 'KEY.return', 'KEYS.return', 'KHC.return', 'KIM.return', 'KKR.return', 'KLAC.return', 'KMB.return', 'KMI.return', 'KMX.return', 'KO.return', 'KR.return', 'KVUE.return', 'L.return', 'LDOS.return', 'LEN.return', 'LH.return', 'LHX.return', 'LII.return', 'LIN.return', 'LKQ.return', 'LLY.return', 'LMT.return', 'LNT.return', 'LOW.return', 'LRCX.return', 'LULU.return', 'LUV.return', 'LVS.return', 'LW.return', 'LYB.return', 'LYV.return', 'MA.return', 'MAA.return', 'MAR.return', 'MAS.return', 'MCD.return', 'MCHP.return', 'MCK.return', 'MCO.return', 'MDLZ.return', 'MDT.return', 'MET.return', 'META.return', 'MGM.return', 'MHK.return', 'MKC.return', 'MKTX.return', 'MLM.return', 'MMC.return', 'MMM.return', 'MNST.return', 'MO.return', 'MOH.return', 'MOS.return', 'MPC.return', 'MPWR.return', 'MRK.return', 'MRNA.return', 'MS.return', 'MSCI.return', 'MSFT.return', 'MSI.return', 'MTB.return', 'MTCH.return', 'MTD.return', 'MU.return', 'NCLH.return', 'NDAQ.return', 'NDSN.return', 'NEE.return', 'NEM.return', 'NFLX.return', 'NI.return', 'NKE.return', 'NOC.return', 'NOW.return', 'NRG.return', 'NSC.return', 'NTAP.return', 'NTRS.return', 'NUE.return', 'NVDA.return', 'NVR.return', 'NWS.return', 'NWSA.return', 'NXPI.return', 'O.return', 'ODFL.return', 'OKE.return', 'OMC.return', 'ON.return', 'ORCL.return', 'ORLY.return', 'OTIS.return', 'OXY.return', 'PANW.return', 'PARA.return', 'PAYC.return', 'PAYX.return', 'PCAR.return', 'PCG.return', 'PEG.return', 'PEP.return', 'PFE.return', 'PFG.return', 'PG.return', 'PGR.return', 'PH.return', 'PHM.return', 'PKG.return', 'PLD.return', 'PLTR.return', 'PM.return', 'PNC.return', 'PNR.return', 'PNW.return', 'PODD.return', 'POOL.return', 'PPG.return', 'PPL.return', 'PRU.return', 'PSA.return', 'PSX.return', 'PTC.return', 'PWR.return', 'PYPL.return', 'QCOM.return', 'RCL.return', 'REG.return', 'REGN.return', 'RF.return', 'RJF.return', 'RL.return', 'RMD.return', 'ROK.return', 'ROL.return', 'ROP.return', 'ROST.return', 'RSG.return', 'RTX.return', 'RVTY.return', 'SBAC.return', 'SBUX.return', 'SCHW.return', 'SHW.return', 'SJM.return', 'SLB.return', 'SMCI.return', 'SNA.return', 'SNPS.return', 'SO.return', 'SOLV.return', 'SPG.return', 'SPGI.return', 'SRE.return', 'STE.return', 'STLD.return', 'STT.return', 'STX.return', 'STZ.return', 'SW.return', 'SWK.return', 'SWKS.return', 'SYF.return', 'SYK.return', 'SYY.return', 'T.return', 'TAP.return', 'TDG.return', 'TDY.return', 'TECH.return', 'TEL.return', 'TER.return', 'TFC.return', 'TFX.return', 'TGT.return', 'TJX.return', 'TMO.return', 'TMUS.return', 'TPL.return', 'TPR.return', 'TRGP.return', 'TRMB.return', 'TROW.return', 'TRV.return', 'TSCO.return', 'TSLA.return', 'TSN.return', 'TT.return', 'TTWO.return', 'TXN.return', 'TXT.return', 'TYL.return', 'UAL.return', 'UBER.return', 'UDR.return', 'UHS.return', 'ULTA.return', 'UNH.return', 'UNP.return', 'UPS.return', 'URI.return', 'USB.return', 'V.return', 'VICI.return', 'VLO.return', 'VLTO.return', 'VMC.return', 'VRSK.return', 'VRSN.return', 'VRTX.return', 'VST.return', 'VTR.return', 'VTRS.return', 'VZ.return', 'WAB.return', 'WAT.return', 'WBA.return', 'WBD.return', 'WDAY.return', 'WDC.return', 'WEC.return', 'WELL.return', 'WFC.return', 'WM.return', 'WMB.return', 'WMT.return', 'WRB.return', 'WST.return', 'WTW.return', 'WY.return', 'WYNN.return', 'XEL.return', 'XOM.return', 'XYL.return', 'YUM.return', 'ZBH.return', 'ZBRA.return', 'ZTS.return']

In [12]:
# COMPUTING EXCESS  RETURNS
# Formula
# Excess Return = Asset Return - Risk-Free Rate

# The Fin-GAN used the U.S. 3-Month Treasury Bill rate as the risk-free rate.
# This is often retrieved from FRED (Federal Reserve Economic Data).

In [13]:
# Retrieving risk-free rate
import pandas_datareader.data as web

# Get 3-Month Treasury Bill Rate from FRED
rf = web.DataReader('TB3MS', 'fred', start='2010-01-01', end='2025-01-01')

# Convert monthly rate (%) to daily and decimal (e.g., 5% -> 0.05)
rf_daily = rf.resample('B').ffill() / 100  # 'B' = business days
rf_daily.rename(columns={'TB3MS': 'risk_free_rate'}, inplace=True)

# Preview
print(rf_daily.head())

            risk_free_rate
DATE
2010-01-01          0.0006
2010-01-04          0.0006
2010-01-05          0.0006
2010-01-06          0.0006
2010-01-07          0.0006

In [19]:
# merge into the return only df (wide format)

# Convert 'Date' to datetime if it's not already
returns_only_df['Date'] = pd.to_datetime(returns_only_df['Date'])

# Merge the risk-free rate dataframe with your returns
excess_returns_df = pd.merge(returns_only_df, rf_daily, left_on='Date', right_index=True, how='left')

# Subtract risk-free rate from each return column
for col in excess_returns_df.columns:
    if col.endswith('.return'):
        excess_returns_df[col] = excess_returns_df[col] - excess_returns_df['risk_free_rate']

# Drop the risk-free rate column if not needed
#excess_returns_df = excess_returns_df.drop(columns=['risk_free_rate'])

#Save to CSV
excess_returns_df.to_csv('excess_returns_only_wide.csv', index=False)

print("Excess returns wide format file saved as excess_returns_only_wide.csv")

Excess returns wide format file saved as excess_returns_only_wide.csv

In [20]:
excess_returns_df.head()

,Date,A.return,AAPL.return,ABBV.return,ABNB.return,ABT.return,ACGL.return,ACN.return,ADBE.return,ADI.return,...,WY.return,WYNN.return,XEL.return,XOM.return,XYL.return,YUM.return,ZBH.return,ZBRA.return,ZTS.return,risk_free_rate
0,2010-03-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0015
1,2010-03-23,0.010066,0.014562,NaN,NaN,0.007225,-0.000170,-0.002207,0.006225,0.010472,...,0.006507,-0.004244,0.000617,-0.001799,NaN,0.001121,0.002968,-0.007474,NaN,0.0015
2,2010-03-24,-0.007657,0.002923,NaN,NaN,-0.010149,0.001158,-0.015887,0.035127,-0.046521,...,-0.008561,-0.008313,-0.011828,-0.008222,NaN,-0.010127,-0.008513,-0.019530,NaN,0.0015
3,2010-03-25,0.017674,-0.013358,NaN,NaN,-0.007997,-0.004150,-0.007961,-0.019029,-0.005630,...,-0.020167,-0.019968,-0.002449,-0.004507,NaN,0.001928,-0.011319,-0.014421,NaN,0.0015
4,2010-03-26,-0.008447,0.017251,NaN,NaN,-0.013084,-0.001101,0.019695,-0.011536,-0.017049,...,0.001670,0.028335,-0.002450,0.002120,NaN,0.004282,-0.004457,0.008490,NaN,0.0015

In [22]:
# Converting excess returns df to long form

# Load the wide format CSV
#excess_returns_df = pd.read_csv('excess_returns_only_wide_format.csv')

# Convert 'Date' to datetime (just in case)
excess_returns_df['Date'] = pd.to_datetime(excess_returns_df['Date'])

# Reshape from wide to long format
# Melt will convert columns like 'AAPL.return' to rows
long_excess_returns = excess_returns_df.melt(
    id_vars=['Date'],
    var_name='Ticker',
    value_name='Excess_Return'
)

# Clean up the 'Ticker' names (remove the '.return' suffix)
long_excess_returns['Ticker'] = long_excess_returns['Ticker'].str.replace('.return', '', regex=False)

# Sort by date and ticker (optional but tidy)
long_excess_returns = long_excess_returns.sort_values(['Date', 'Ticker']).reset_index(drop=True)

# Save to CSV
long_excess_returns.to_csv('excess_returns_long_format.csv', index=False)

print(" Long format file saved as excess_returns_long_format.csv")

 Long format file saved as excess_returns_long_format.csv

In [26]:
long_excess_returns.head(1000)

          Date Ticker  Excess_Return
0   2010-03-22      A            NaN
1   2010-03-22   AAPL            NaN
2   2010-03-22   ABBV            NaN
3   2010-03-22   ABNB            NaN
4   2010-03-22    ABT            NaN
..         ...    ...            ...
995 2010-03-23    WRB       0.002799
996 2010-03-23    WST       0.012090
997 2010-03-23    WTW       0.008307
998 2010-03-23     WY       0.006507
999 2010-03-23   WYNN      -0.004244

[1000 rows x 3 columns]

In [27]:
# CREATING PER-TICKER FILES
# USING EXCESS RETURNS

#Load the long format data
long_excess_returns = pd.read_csv('excess_returns_long_format.csv')

#Create an output folder
output_folder = 'fin_gan_ticker_data'
os.makedirs(output_folder, exist_ok=True)

#Group by ticker and save each as a separate CSV
tickers = long_excess_returns['Ticker'].unique()

for ticker in tickers:
    ticker_df = long_excess_returns[long_excess_returns['Ticker'] == ticker][['Date', 'Excess_Return']]
    
    # Optional: Sort by Date (safety step)
    ticker_df = ticker_df.sort_values('Date').reset_index(drop=True)
    
    # Save the file
    file_path = os.path.join(output_folder, f'{ticker}-data.csv')
    ticker_df.to_csv(file_path, index=False)
    
    print(f"✅ Saved {file_path} with {len(ticker_df)} rows")

print("All per-ticker files generated and ready")

✅ Saved fin_gan_ticker_data/A-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AAPL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ABBV-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ABNB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ABT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ACGL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ACN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ADBE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ADI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ADM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ADP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ADSK-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AEE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AEP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AES-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AFL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AIG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AIZ-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AJG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AKAM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ALB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ALGN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ALL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ALLE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AMAT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AMCR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AMD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AME-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AMGN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AMP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AMT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AMZN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ANET-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ANSS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AON-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AOS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/APA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/APD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/APH-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/APO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/APTV-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ARE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ATO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AVB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AVGO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AVY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AWK-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AXON-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AXP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/AZO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BAC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BALL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BAX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BBY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BDX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BEN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BF-B-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BIIB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BK-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BKNG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BKR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BLDR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BLK-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BMY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BRK-B-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BRO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BSX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BWA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/BXP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/C-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CAG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CAH-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CARR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CAT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CBOE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CBRE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CCI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CCL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CDNS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CDW-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CEG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CF-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CFG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CHD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CHRW-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CHTR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CINF-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CLX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CMCSA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CME-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CMG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CMI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CMS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CNC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CNP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/COF-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/COO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/COP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/COR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/COST-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CPAY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CPB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CPRT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CPT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CRL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CRM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CRWD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CSCO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CSGP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CSX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CTAS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CTRA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CTSH-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CTVA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CVS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CVX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/CZR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/D-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DAL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DAY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DECK-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DELL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DFS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DGX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DHI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DHR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DIS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DLR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DLTR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DOC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DOV-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DOW-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DPZ-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DRI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DTE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DUK-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DVA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DVN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/DXCM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EBAY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ECL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ED-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EFX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EIX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ELV-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EMN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EMR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ENPH-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EOG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EPAM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EQIX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EQR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EQT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ERIE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ES-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ESS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ETN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ETR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EVRG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EW-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EXC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EXPD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EXPE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/EXR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/F-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FANG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FAST-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FCX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FDS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FDX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FFIV-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FICO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FIS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FITB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FMC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FOX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FOXA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FRT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FSLR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FTNT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/FTV-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GDDY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GEHC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GEN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GEV-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GILD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GIS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GLW-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GNRC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GOOG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GOOGL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GPC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GPN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GRMN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/GWW-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HAL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HAS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HBAN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HCA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HES-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HIG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HII-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HLT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HOLX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HON-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HPE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HPQ-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HRL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HSIC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HST-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HSY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HUBB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HUM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/HWM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IBM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ICE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IDXX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IEX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IFF-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/INCY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/INTC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/INTU-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/INVH-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IPG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IQV-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IRM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ISRG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ITW-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/IVZ-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/J-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/JBHT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/JBL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/JCI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/JKHY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/JNJ-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/JNPR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/JPM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/K-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KDP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KEY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KEYS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KHC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KIM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KKR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KLAC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KMB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KMI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KMX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/KVUE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/L-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LDOS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LEN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LH-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LHX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LII-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LIN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LKQ-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LLY-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LMT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LNT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LOW-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LRCX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LULU-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LUV-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LVS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LW-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LYB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/LYV-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MAA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MAR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MAS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MCD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MCHP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MCK-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MCO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MDLZ-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MDT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MET-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/META-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MGM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MHK-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MKC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MKTX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MLM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MMC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MMM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MNST-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MO-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MOH-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MOS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MPC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MPWR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MRK-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MRNA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MSCI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MSFT-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MSI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MTB-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MTCH-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MTD-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/MU-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NCLH-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NDAQ-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NDSN-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NEE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NEM-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NFLX-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NKE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NOC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NOW-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NRG-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NSC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NTAP-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NTRS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NUE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NVDA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NVR-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NWS-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NWSA-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/NXPI-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/O-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ODFL-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/OKE-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/OMC-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ON-data.csv with 3770 rows
✅ Saved fin_gan_ticker_data/ORCL-data.csv with 3770 rows

In [28]:
# HERE we
# Groups by ticker
#Extract only the Date and Excess_Return columns
#Save each ticker’s data to a Fin-GAN ready CSV file

###  ETF Data preparation

In [29]:
# Computing DAILY RETURNS

# Load ETF data
etf_data = pd.read_csv('etf_data.csv')

# Convert Date to datetime
etf_data['Date'] = pd.to_datetime(etf_data['Date'])
# Sort by Date
etf_data = etf_data.sort_values('Date')

# Compute daily returns for each ETF
for col in etf_data.columns:
    if col.endswith('.close'):
        ticker = col.replace('.close', '')
        return_col = ticker + '.return'
        
        etf_data[return_col] = etf_data[col].pct_change()

# Save the returns-only wide file (optional)
returns_only_cols = ['Date'] + [col for col in etf_data.columns if col.endswith('.return')]
etf_returns_only_df = etf_data[returns_only_cols]

etf_returns_only_df.to_csv('etf_returns_only_wide.csv', index=False)

print(" ETF daily returns computed and saved as etf_returns_only_wide.csv")

 ETF daily returns computed and saved as etf_returns_only_wide.csv

In [30]:
print(etf_returns_only_df.head())

        Date  XLB.return  XLC.return  XLE.return  XLF.return  XLI.return  \
0 2010-03-22         NaN         NaN         NaN         NaN         NaN
1 2010-03-23    0.013029         NaN    0.003851    0.008243    0.011327
2 2010-03-24   -0.002924         NaN   -0.005754    0.000629   -0.007040
3 2010-03-25   -0.019935         NaN   -0.016836    0.004400   -0.000645
4 2010-03-26    0.007478         NaN    0.000357    0.001252    0.002580

   XLK.return  XLP.return  XLRE.return  XLU.return  XLV.return  XLY.return
0         NaN         NaN          NaN         NaN         NaN         NaN
1    0.009582    0.007883          NaN    0.004032    0.004929    0.003971
2   -0.004745   -0.007110          NaN   -0.010375   -0.010730   -0.003955
3    0.001734   -0.001432          NaN   -0.006426   -0.004029    0.005803
4   -0.004760    0.000717          NaN    0.002383   -0.007467    0.003948

In [31]:
# COMPUTE EXCESS RETURNS (Subtracting free-risk rate)

# Merge risk-free rate (rf_daily) with ETF returns
etf_excess_returns_df = pd.merge(etf_returns_only_df, rf_daily, left_on='Date', right_index=True, how='left')

# Subtract risk-free rate from each return column
for col in etf_excess_returns_df.columns:
    if col.endswith('.return'):
        etf_excess_returns_df[col] = etf_excess_returns_df[col] - etf_excess_returns_df['risk_free_rate']

# Drop risk-free rate column if not needed
#etf_excess_returns_df = etf_excess_returns_df.drop(columns=['risk_free_rate'])

# Save excess returns wide format
etf_excess_returns_df.to_csv('etf_excess_returns_only_wide.csv', index=False)

print("✅ ETF excess returns wide format file saved as etf_excess_returns_only_wide.csv")

✅ ETF excess returns wide format file saved as etf_excess_returns_only_wide.csv

In [32]:
# Converting from wide to LONG FORMAT

# Melt the wide format to long
long_etf_excess_returns = etf_excess_returns_df.melt(
    id_vars=['Date'],
    var_name='Ticker',
    value_name='Excess_Return'
)

# Clean ticker names
long_etf_excess_returns['Ticker'] = long_etf_excess_returns['Ticker'].str.replace('.return', '', regex=False)

# Sort by Date and Ticker
long_etf_excess_returns = long_etf_excess_returns.sort_values(['Date', 'Ticker']).reset_index(drop=True)

# Save to long format CSV
long_etf_excess_returns.to_csv('etf_excess_returns_long_format.csv', index=False)

print("✅ Long format ETF excess returns saved as etf_excess_returns_long_format.csv")

✅ Long format ETF excess returns saved as etf_excess_returns_long_format.csv

In [33]:
# Generate Per-ETF Files 

# create output folder
etf_output_folder = 'fin_gan_etf_data'
os.makedirs(etf_output_folder, exist_ok=True)

# Get list of ETFs
etf_tickers = long_etf_excess_returns['Ticker'].unique()

#Save per-ETF files
for ticker in etf_tickers:
    etf_ticker_df = long_etf_excess_returns[long_etf_excess_returns['Ticker'] == ticker][['Date', 'Excess_Return']]
    
    # Sort by Date for consistency
    etf_ticker_df = etf_ticker_df.sort_values('Date').reset_index(drop=True)
    
    # Save to CSV
    file_path = os.path.join(etf_output_folder, f'{ticker}-data.csv')
    etf_ticker_df.to_csv(file_path, index=False)
    
    print(f"✅ Saved {file_path} with {len(etf_ticker_df)} rows")

print("All per-ETF files generated")

✅ Saved fin_gan_etf_data/XLB-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/XLC-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/XLE-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/XLF-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/XLI-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/XLK-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/XLP-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/XLRE-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/XLU-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/XLV-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/XLY-data.csv with 3770 rows
✅ Saved fin_gan_etf_data/risk_free_rate-data.csv with 3770 rows
All per-ETF files generated

In [ ]:
# File saving in the dataset folder for replication - STOCK (TICKER)

# # Load the long format excess returns file
# long_excess_returns = pd.read_csv('excess_returns_long_format.csv')

# # Define the correct output path
# output_folder = 'Fin-GAN-main/datasets'  # Already inside Fin-GAN-main/
# assert os.path.exists(output_folder), f"❌ Folder '{output_folder}' not found!"

# # Loop through each ticker and create the expected CSV
# tickers = long_excess_returns['Ticker'].unique()

# for ticker in tickers:
#     df = long_excess_returns[long_excess_returns['Ticker'] == ticker][['Date', 'Excess_Return']].copy()
#     df.dropna(inplace=True)
#     df = df.sort_values('Date').reset_index(drop=True)
    
#     # Rename columns as Fin-GAN expects
#     df.rename(columns={'Date': 'date', 'Excess_Return': 'ret'}, inplace=True)
    
#     # Save to CSV
#     df.to_csv(os.path.join(output_folder, f'{ticker}.csv'), index=False)
#     print(f"✅ Saved {ticker}.csv with {len(df)} rows")

# print("🎉 All per-ticker files successfully created and saved in datasets")

In [ ]:
# ETF

# # Confirm the output folder path
# etf_output_folder = 'Fin-GAN-main/datasets' 

# # Make sure folder exists
# os.makedirs(etf_output_folder, exist_ok=True)

# # Load data
# long_etf_excess_returns = pd.read_csv('etf_excess_returns_long_format.csv')
# # Unique ETF tickers
# etf_tickers = long_etf_excess_returns['Ticker'].unique()

# # Save per-ETF CSVs
# for ticker in etf_tickers:
#     etf_ticker_df = long_etf_excess_returns[long_etf_excess_returns['Ticker'] == ticker][['Excess_Return']]
    
#     # Rename column to "ret" (what FinGAN expects)
#     etf_ticker_df = etf_ticker_df.rename(columns={'Excess_Return': 'ret'}).reset_index(drop=True)
    
#     # Save without date
#     file_path = os.path.join(etf_output_folder, f'{ticker}.csv')
#     etf_ticker_df.to_csv(file_path, index=False)

#     print(f"✅ Saved {file_path} with {len(etf_ticker_df)} rows")

# print("📦 All per-ETF files saved to 'datasets/' folder.")

### ALIGNING WITH FIN GAN

In [10]:
# we rename ret to AdjClose for compatibility with code

# === STOCKS ===
import pandas as pd
import os

# Load your wide-format stock data
stock_data = pd.read_csv('stock_data.csv')
stock_data['Date'] = pd.to_datetime(stock_data['Date'])

# Create output folder for Fin-GAN
output_path = 'Fin-GAN-main/datasets'
os.makedirs(output_path, exist_ok=True)

# Get all unique tickers by splitting column names
tickers = set()
for col in stock_data.columns:
    if '.close' in col:
        tickers.add(col.replace('.close', ''))

# Loop through tickers and extract their data
for ticker in sorted(tickers):
    close_col = f"{ticker}.close"
    open_col = f"{ticker}.open"
    
    if close_col in stock_data.columns and open_col in stock_data.columns:
        df = stock_data[['Date', close_col, open_col]].copy()
        df = df.rename(columns={
            'Date': 'date',
            close_col: 'AdjClose',
            open_col: 'AdjOpen'
        })
        df = df.dropna().sort_values('date').reset_index(drop=True)

        # Save to CSV
        file_path = os.path.join(output_path, f"{ticker}.csv")
        df.to_csv(file_path, index=False)
        print(f"✅ Saved {ticker}.csv with {len(df)} rows")

print("🎯 All stock CSVs are now Fin-GAN-ready!")

/var/folders/k1/p_xw0_4x4zd812685rsx20380000gn/T/ipykernel_36895/1694104234.py:9: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  stock_data['Date'] = pd.to_datetime(stock_data['Date'])

✅ Saved A.csv with 3770 rows
✅ Saved AAPL.csv with 3770 rows
✅ Saved ABBV.csv with 3069 rows
✅ Saved ABNB.csv with 1069 rows
✅ Saved ABT.csv with 3770 rows
✅ Saved ACGL.csv with 3770 rows
✅ Saved ACN.csv with 3770 rows
✅ Saved ADBE.csv with 3770 rows
✅ Saved ADI.csv with 3770 rows
✅ Saved ADM.csv with 3770 rows
✅ Saved ADP.csv with 3770 rows
✅ Saved ADSK.csv with 3770 rows
✅ Saved AEE.csv with 3770 rows
✅ Saved AEP.csv with 3770 rows
✅ Saved AES.csv with 3770 rows
✅ Saved AFL.csv with 3770 rows
✅ Saved AIG.csv with 3770 rows
✅ Saved AIZ.csv with 3770 rows
✅ Saved AJG.csv with 3770 rows
✅ Saved AKAM.csv with 3770 rows
✅ Saved ALB.csv with 3770 rows
✅ Saved ALGN.csv with 3770 rows
✅ Saved ALL.csv with 3770 rows
✅ Saved ALLE.csv with 2847 rows
✅ Saved AMAT.csv with 3770 rows
✅ Saved AMCR.csv with 3227 rows
✅ Saved AMD.csv with 3770 rows
✅ Saved AME.csv with 3770 rows
✅ Saved AMGN.csv with 3770 rows
✅ Saved AMP.csv with 3770 rows
✅ Saved AMT.csv with 3770 rows
✅ Saved AMZN.csv with 3770 rows
✅ Saved ANET.csv with 2710 rows
✅ Saved ANSS.csv with 3770 rows
✅ Saved AON.csv with 3770 rows
✅ Saved AOS.csv with 3770 rows
✅ Saved APA.csv with 3770 rows
✅ Saved APD.csv with 3770 rows
✅ Saved APH.csv with 3770 rows
✅ Saved APO.csv with 3511 rows
✅ Saved APTV.csv with 3349 rows
✅ Saved ARE.csv with 3770 rows
✅ Saved ATO.csv with 3770 rows
✅ Saved AVB.csv with 3770 rows
✅ Saved AVGO.csv with 3770 rows
✅ Saved AVY.csv with 3770 rows
✅ Saved AWK.csv with 3770 rows
✅ Saved AXON.csv with 3770 rows
✅ Saved AXP.csv with 3770 rows
✅ Saved AZO.csv with 3770 rows
✅ Saved BA.csv with 3770 rows
✅ Saved BAC.csv with 3770 rows
✅ Saved BALL.csv with 3770 rows
✅ Saved BAX.csv with 3770 rows
✅ Saved BBY.csv with 3770 rows
✅ Saved BDX.csv with 3770 rows
✅ Saved BEN.csv with 3770 rows
✅ Saved BF-B.csv with 3770 rows
✅ Saved BG.csv with 3770 rows
✅ Saved BIIB.csv with 3770 rows
✅ Saved BK.csv with 3770 rows
✅ Saved BKNG.csv with 3770 rows
✅ Saved BKR.csv with 3770 rows
✅ Saved BLDR.csv with 3770 rows
✅ Saved BLK.csv with 3770 rows
✅ Saved BMY.csv with 3770 rows
✅ Saved BR.csv with 3770 rows
✅ Saved BRK-B.csv with 3770 rows
✅ Saved BRO.csv with 3770 rows
✅ Saved BSX.csv with 3770 rows
✅ Saved BWA.csv with 3770 rows
✅ Saved BX.csv with 3770 rows
✅ Saved BXP.csv with 3770 rows
✅ Saved C.csv with 3770 rows
✅ Saved CAG.csv with 3770 rows
✅ Saved CAH.csv with 3770 rows
✅ Saved CARR.csv with 1254 rows
✅ Saved CAT.csv with 3770 rows
✅ Saved CB.csv with 3770 rows
✅ Saved CBOE.csv with 3711 rows
✅ Saved CBRE.csv with 3770 rows
✅ Saved CCI.csv with 3770 rows
✅ Saved CCL.csv with 3770 rows
✅ Saved CDNS.csv with 3770 rows
✅ Saved CDW.csv with 2947 rows
✅ Saved CE.csv with 3770 rows
✅ Saved CEG.csv with 791 rows
✅ Saved CF.csv with 3770 rows
✅ Saved CFG.csv with 2634 rows
✅ Saved CHD.csv with 3770 rows
✅ Saved CHRW.csv with 3770 rows
✅ Saved CHTR.csv with 3770 rows
✅ Saved CI.csv with 3770 rows
✅ Saved CINF.csv with 3770 rows
✅ Saved CL.csv with 3770 rows
✅ Saved CLX.csv with 3770 rows
✅ Saved CMCSA.csv with 3770 rows
✅ Saved CME.csv with 3770 rows
✅ Saved CMG.csv with 3770 rows
✅ Saved CMI.csv with 3770 rows
✅ Saved CMS.csv with 3770 rows
✅ Saved CNC.csv with 3770 rows
✅ Saved CNP.csv with 3770 rows
✅ Saved COF.csv with 3770 rows
✅ Saved COO.csv with 3770 rows
✅ Saved COP.csv with 3770 rows
✅ Saved COR.csv with 3770 rows
✅ Saved COST.csv with 3770 rows
✅ Saved CPAY.csv with 3583 rows
✅ Saved CPB.csv with 3770 rows
✅ Saved CPRT.csv with 3770 rows
✅ Saved CPT.csv with 3770 rows
✅ Saved CRL.csv with 3770 rows
✅ Saved CRM.csv with 3770 rows
✅ Saved CRWD.csv with 1448 rows
✅ Saved CSCO.csv with 3770 rows
✅ Saved CSGP.csv with 3770 rows
✅ Saved CSX.csv with 3770 rows
✅ Saved CTAS.csv with 0 rows
✅ Saved CTRA.csv with 3770 rows
✅ Saved CTSH.csv with 3770 rows
✅ Saved CTVA.csv with 1460 rows
✅ Saved CVS.csv with 3770 rows
✅ Saved CVX.csv with 3770 rows
✅ Saved CZR.csv with 2636 rows
✅ Saved D.csv with 3770 rows
✅ Saved DAL.csv with 3770 rows
✅ Saved DAY.csv with 1731 rows
✅ Saved DD.csv with 3770 rows
✅ Saved DE.csv with 3770 rows
✅ Saved DECK.csv with 3770 rows
✅ Saved DELL.csv with 2156 rows
✅ Saved DFS.csv with 3770 rows
✅ Saved DG.csv with 3770 rows
✅ Saved DGX.csv with 3770 rows
✅ Saved DHI.csv with 3770 rows
✅ Saved DHR.csv with 3770 rows
✅ Saved DIS.csv with 3770 rows
✅ Saved DLR.csv with 3770 rows
✅ Saved DLTR.csv with 3770 rows
✅ Saved DOC.csv with 3770 rows
✅ Saved DOV.csv with 3770 rows
✅ Saved DOW.csv with 1506 rows
✅ Saved DPZ.csv with 3770 rows
✅ Saved DRI.csv with 3770 rows
✅ Saved DTE.csv with 3770 rows
✅ Saved DUK.csv with 3770 rows
✅ Saved DVA.csv with 3770 rows
✅ Saved DVN.csv with 3770 rows
✅ Saved DXCM.csv with 3770 rows
✅ Saved EA.csv with 3770 rows
✅ Saved EBAY.csv with 3770 rows
✅ Saved ECL.csv with 3770 rows
✅ Saved ED.csv with 3770 rows
✅ Saved EFX.csv with 3770 rows
✅ Saved EG.csv with 3770 rows
✅ Saved EIX.csv with 3770 rows
✅ Saved EL.csv with 3770 rows
✅ Saved ELV.csv with 3770 rows
✅ Saved EMN.csv with 3770 rows
✅ Saved EMR.csv with 3770 rows
✅ Saved ENPH.csv with 3258 rows
✅ Saved EOG.csv with 3770 rows
✅ Saved EPAM.csv with 3294 rows
✅ Saved EQIX.csv with 3770 rows
✅ Saved EQR.csv with 3770 rows
✅ Saved EQT.csv with 3770 rows
✅ Saved ERIE.csv with 3770 rows
✅ Saved ES.csv with 3770 rows
✅ Saved ESS.csv with 3770 rows
✅ Saved ETN.csv with 3770 rows
✅ Saved ETR.csv with 0 rows
✅ Saved EVRG.csv with 3770 rows
✅ Saved EW.csv with 3770 rows
✅ Saved EXC.csv with 3770 rows
✅ Saved EXPD.csv with 3770 rows
✅ Saved EXPE.csv with 3770 rows
✅ Saved EXR.csv with 3770 rows
✅ Saved F.csv with 3770 rows
✅ Saved FANG.csv with 3122 rows
✅ Saved FAST.csv with 3770 rows
✅ Saved FCX.csv with 3770 rows
✅ Saved FDS.csv with 3770 rows
✅ Saved FDX.csv with 3770 rows
✅ Saved FE.csv with 3770 rows
✅ Saved FFIV.csv with 3770 rows
✅ Saved FI.csv with 3770 rows
✅ Saved FICO.csv with 3770 rows
✅ Saved FIS.csv with 3770 rows
✅ Saved FITB.csv with 3770 rows
✅ Saved FMC.csv with 3770 rows
✅ Saved FOX.csv with 1511 rows
✅ Saved FOXA.csv with 1512 rows
✅ Saved FRT.csv with 3770 rows
✅ Saved FSLR.csv with 3770 rows
✅ Saved FTNT.csv with 3770 rows
✅ Saved FTV.csv with 2187 rows
✅ Saved GD.csv with 3770 rows
✅ Saved GDDY.csv with 2505 rows
✅ Saved GE.csv with 3770 rows
✅ Saved GEHC.csv with 562 rows
✅ Saved GEN.csv with 3770 rows
✅ Saved GEV.csv with 240 rows
✅ Saved GILD.csv with 3770 rows
✅ Saved GIS.csv with 3770 rows
✅ Saved GL.csv with 3770 rows
✅ Saved GLW.csv with 3770 rows
✅ Saved GM.csv with 3601 rows
✅ Saved GNRC.csv with 3770 rows
✅ Saved GOOG.csv with 3770 rows
✅ Saved GOOGL.csv with 3770 rows
✅ Saved GPC.csv with 3770 rows
✅ Saved GPN.csv with 3770 rows
✅ Saved GRMN.csv with 3770 rows
✅ Saved GS.csv with 3770 rows
✅ Saved GWW.csv with 3770 rows
✅ Saved HAL.csv with 3770 rows
✅ Saved HAS.csv with 3770 rows
✅ Saved HBAN.csv with 3770 rows
✅ Saved HCA.csv with 3525 rows
✅ Saved HD.csv with 3770 rows
✅ Saved HES.csv with 3770 rows
✅ Saved HIG.csv with 3770 rows
✅ Saved HII.csv with 3517 rows
✅ Saved HLT.csv with 2830 rows
✅ Saved HOLX.csv with 3770 rows
✅ Saved HON.csv with 3770 rows
✅ Saved HPE.csv with 2365 rows
✅ Saved HPQ.csv with 3770 rows
✅ Saved HRL.csv with 3770 rows
✅ Saved HSIC.csv with 3770 rows
✅ Saved HST.csv with 3770 rows
✅ Saved HSY.csv with 3770 rows
✅ Saved HUBB.csv with 3770 rows
✅ Saved HUM.csv with 3770 rows
✅ Saved HWM.csv with 2103 rows
✅ Saved IBM.csv with 3770 rows
✅ Saved ICE.csv with 3770 rows
✅ Saved IDXX.csv with 3770 rows
✅ Saved IEX.csv with 3770 rows
✅ Saved IFF.csv with 3770 rows
✅ Saved INCY.csv with 3770 rows
✅ Saved INTC.csv with 3770 rows
✅ Saved INTU.csv with 3770 rows
✅ Saved INVH.csv with 2041 rows
✅ Saved IP.csv with 3770 rows
✅ Saved IPG.csv with 3770 rows
✅ Saved IQV.csv with 2981 rows
✅ Saved IR.csv with 1971 rows
✅ Saved IRM.csv with 3770 rows
✅ Saved ISRG.csv with 3770 rows
✅ Saved IT.csv with 3770 rows
✅ Saved ITW.csv with 3770 rows
✅ Saved IVZ.csv with 3770 rows
✅ Saved J.csv with 3770 rows
✅ Saved JBHT.csv with 3770 rows
✅ Saved JBL.csv with 3770 rows
✅ Saved JCI.csv with 3770 rows
✅ Saved JKHY.csv with 3770 rows
✅ Saved JNJ.csv with 3770 rows
✅ Saved JNPR.csv with 3770 rows
✅ Saved JPM.csv with 3770 rows
✅ Saved K.csv with 3770 rows
✅ Saved KDP.csv with 3770 rows
✅ Saved KEY.csv with 3770 rows
✅ Saved KEYS.csv with 2616 rows
✅ Saved KHC.csv with 2439 rows
✅ Saved KIM.csv with 3770 rows
✅ Saved KKR.csv with 3690 rows
✅ Saved KLAC.csv with 3770 rows
✅ Saved KMB.csv with 3770 rows
✅ Saved KMI.csv with 3543 rows
✅ Saved KMX.csv with 3770 rows
✅ Saved KO.csv with 3770 rows
✅ Saved KR.csv with 3770 rows
✅ Saved KVUE.csv with 467 rows
✅ Saved L.csv with 3770 rows
✅ Saved LDOS.csv with 3770 rows
✅ Saved LEN.csv with 3770 rows
✅ Saved LH.csv with 3770 rows
✅ Saved LHX.csv with 3770 rows
✅ Saved LII.csv with 3770 rows
✅ Saved LIN.csv with 3770 rows
✅ Saved LKQ.csv with 3770 rows
✅ Saved LLY.csv with 3770 rows
✅ Saved LMT.csv with 3770 rows
✅ Saved LNT.csv with 3770 rows
✅ Saved LOW.csv with 3770 rows
✅ Saved LRCX.csv with 3770 rows
✅ Saved LULU.csv with 3770 rows
✅ Saved LUV.csv with 3770 rows
✅ Saved LVS.csv with 3770 rows
✅ Saved LW.csv with 2096 rows
✅ Saved LYB.csv with 3744 rows
✅ Saved LYV.csv with 3770 rows
✅ Saved MA.csv with 3770 rows
✅ Saved MAA.csv with 3770 rows
✅ Saved MAR.csv with 3770 rows
✅ Saved MAS.csv with 3770 rows
✅ Saved MCD.csv with 3770 rows
✅ Saved MCHP.csv with 3770 rows
✅ Saved MCK.csv with 3770 rows
✅ Saved MCO.csv with 3770 rows
✅ Saved MDLZ.csv with 3770 rows
✅ Saved MDT.csv with 3770 rows
✅ Saved MET.csv with 3770 rows
✅ Saved META.csv with 3224 rows
✅ Saved MGM.csv with 3770 rows
✅ Saved MHK.csv with 3770 rows
✅ Saved MKC.csv with 3770 rows
✅ Saved MKTX.csv with 3770 rows
✅ Saved MLM.csv with 3770 rows
✅ Saved MMC.csv with 3770 rows
✅ Saved MMM.csv with 3770 rows
✅ Saved MNST.csv with 3770 rows
✅ Saved MO.csv with 3770 rows
✅ Saved MOH.csv with 3770 rows
✅ Saved MOS.csv with 3770 rows
✅ Saved MPC.csv with 3451 rows
✅ Saved MPWR.csv with 3770 rows
✅ Saved MRK.csv with 3770 rows
✅ Saved MRNA.csv with 1575 rows
✅ Saved MS.csv with 3770 rows
✅ Saved MSCI.csv with 3770 rows
✅ Saved MSFT.csv with 3770 rows
✅ Saved MSI.csv with 3770 rows
✅ Saved MTB.csv with 3770 rows
✅ Saved MTCH.csv with 3770 rows
✅ Saved MTD.csv with 3770 rows
✅ Saved MU.csv with 3770 rows
✅ Saved NCLH.csv with 3057 rows
✅ Saved NDAQ.csv with 3770 rows
✅ Saved NDSN.csv with 3770 rows
✅ Saved NEE.csv with 3770 rows
✅ Saved NEM.csv with 3770 rows
✅ Saved NFLX.csv with 3770 rows
✅ Saved NI.csv with 3770 rows
✅ Saved NKE.csv with 3770 rows
✅ Saved NOC.csv with 3770 rows
✅ Saved NOW.csv with 3195 rows
✅ Saved NRG.csv with 3770 rows
✅ Saved NSC.csv with 3770 rows
✅ Saved NTAP.csv with 3770 rows
✅ Saved NTRS.csv with 3770 rows
✅ Saved NUE.csv with 3770 rows
✅ Saved NVDA.csv with 3770 rows
✅ Saved NVR.csv with 3770 rows
✅ Saved NWS.csv with 2953 rows
✅ Saved NWSA.csv with 2953 rows
✅ Saved NXPI.csv with 3674 rows
✅ Saved O.csv with 3770 rows
✅ Saved ODFL.csv with 3770 rows
✅ Saved OKE.csv with 3770 rows
✅ Saved OMC.csv with 3770 rows
✅ Saved ON.csv with 3770 rows
✅ Saved ORCL.csv with 3770 rows
✅ Saved ORLY.csv with 3770 rows
✅ Saved OTIS.csv with 1254 rows
✅ Saved OXY.csv with 3770 rows
✅ Saved PANW.csv with 3181 rows
✅ Saved PARA.csv with 3770 rows
✅ Saved PAYC.csv with 2746 rows
✅ Saved PAYX.csv with 3770 rows
✅ Saved PCAR.csv with 3770 rows
✅ Saved PCG.csv with 3770 rows
✅ Saved PEG.csv with 3770 rows
✅ Saved PEP.csv with 3770 rows
✅ Saved PFE.csv with 3770 rows
✅ Saved PFG.csv with 3770 rows
✅ Saved PG.csv with 3770 rows
✅ Saved PGR.csv with 3770 rows
✅ Saved PH.csv with 3770 rows
✅ Saved PHM.csv with 3770 rows
✅ Saved PKG.csv with 3770 rows
✅ Saved PLD.csv with 3770 rows
✅ Saved PLTR.csv with 1119 rows
✅ Saved PM.csv with 3770 rows
✅ Saved PNC.csv with 3770 rows
✅ Saved PNR.csv with 3770 rows
✅ Saved PNW.csv with 3770 rows
✅ Saved PODD.csv with 3770 rows
✅ Saved POOL.csv with 3770 rows
✅ Saved PPG.csv with 3770 rows
✅ Saved PPL.csv with 3770 rows
✅ Saved PRU.csv with 3770 rows
✅ Saved PSA.csv with 3770 rows
✅ Saved PSX.csv with 3250 rows
✅ Saved PTC.csv with 3770 rows
✅ Saved PWR.csv with 3770 rows
✅ Saved PYPL.csv with 2439 rows
✅ Saved QCOM.csv with 3770 rows
✅ Saved RCL.csv with 3770 rows
✅ Saved REG.csv with 3770 rows
✅ Saved REGN.csv with 3770 rows
✅ Saved RF.csv with 3770 rows
✅ Saved RJF.csv with 3770 rows
✅ Saved RL.csv with 3770 rows
✅ Saved RMD.csv with 3770 rows
✅ Saved ROK.csv with 3770 rows
✅ Saved ROL.csv with 3770 rows
✅ Saved ROP.csv with 3770 rows
✅ Saved ROST.csv with 3770 rows
✅ Saved RSG.csv with 3770 rows
✅ Saved RTX.csv with 3770 rows
✅ Saved RVTY.csv with 3770 rows
✅ Saved SBAC.csv with 3770 rows
✅ Saved SBUX.csv with 3770 rows
✅ Saved SCHW.csv with 3770 rows
✅ Saved SHW.csv with 3770 rows
✅ Saved SJM.csv with 3770 rows
✅ Saved SLB.csv with 3770 rows
✅ Saved SMCI.csv with 3770 rows
✅ Saved SNA.csv with 3770 rows
✅ Saved SNPS.csv with 3770 rows
✅ Saved SO.csv with 3770 rows
✅ Saved SOLV.csv with 240 rows
✅ Saved SPG.csv with 3770 rows
✅ Saved SPGI.csv with 3770 rows
✅ Saved SRE.csv with 3770 rows
✅ Saved STE.csv with 3770 rows
✅ Saved STLD.csv with 3770 rows
✅ Saved STT.csv with 3770 rows
✅ Saved STX.csv with 3770 rows
✅ Saved STZ.csv with 3770 rows
✅ Saved SW.csv with 173 rows
✅ Saved SWK.csv with 3770 rows
✅ Saved SWKS.csv with 3770 rows
✅ Saved SYF.csv with 2672 rows
✅ Saved SYK.csv with 3770 rows
✅ Saved SYY.csv with 3770 rows
✅ Saved T.csv with 3770 rows
✅ Saved TAP.csv with 3770 rows
✅ Saved TDG.csv with 3770 rows
✅ Saved TDY.csv with 3770 rows
✅ Saved TECH.csv with 3770 rows
✅ Saved TEL.csv with 3770 rows
✅ Saved TER.csv with 3770 rows
✅ Saved TFC.csv with 3770 rows
✅ Saved TFX.csv with 3770 rows
✅ Saved TGT.csv with 3770 rows
✅ Saved TJX.csv with 3770 rows
✅ Saved TMO.csv with 3770 rows
✅ Saved TMUS.csv with 3770 rows
✅ Saved TPL.csv with 3770 rows
✅ Saved TPR.csv with 3770 rows
✅ Saved TRGP.csv with 3589 rows
✅ Saved TRMB.csv with 3770 rows
✅ Saved TROW.csv with 3770 rows
✅ Saved TRV.csv with 3770 rows
✅ Saved TSCO.csv with 3770 rows
✅ Saved TSLA.csv with 3701 rows
✅ Saved TSN.csv with 3770 rows
✅ Saved TT.csv with 3770 rows
✅ Saved TTWO.csv with 3770 rows
✅ Saved TXN.csv with 3770 rows
✅ Saved TXT.csv with 3770 rows
✅ Saved TYL.csv with 3770 rows
✅ Saved UAL.csv with 3770 rows
✅ Saved UBER.csv with 1470 rows
✅ Saved UDR.csv with 3770 rows
✅ Saved UHS.csv with 3770 rows
✅ Saved ULTA.csv with 3770 rows
✅ Saved UNH.csv with 3770 rows
✅ Saved UNP.csv with 3770 rows
✅ Saved UPS.csv with 3770 rows
✅ Saved URI.csv with 3770 rows
✅ Saved USB.csv with 3770 rows
✅ Saved V.csv with 3770 rows
✅ Saved VICI.csv with 1810 rows
✅ Saved VLO.csv with 3770 rows
✅ Saved VLTO.csv with 362 rows
✅ Saved VMC.csv with 3770 rows
✅ Saved VRSK.csv with 3770 rows
✅ Saved VRSN.csv with 3770 rows
✅ Saved VRTX.csv with 3770 rows
✅ Saved VST.csv with 2122 rows
✅ Saved VTR.csv with 3770 rows
✅ Saved VTRS.csv with 3770 rows
✅ Saved VZ.csv with 3770 rows
✅ Saved WAB.csv with 3770 rows
✅ Saved WAT.csv with 3770 rows
✅ Saved WBA.csv with 3770 rows
✅ Saved WBD.csv with 3770 rows
✅ Saved WDAY.csv with 3122 rows
✅ Saved WDC.csv with 3770 rows
✅ Saved WEC.csv with 3770 rows
✅ Saved WELL.csv with 3770 rows
✅ Saved WFC.csv with 3770 rows
✅ Saved WM.csv with 3770 rows
✅ Saved WMB.csv with 3770 rows
✅ Saved WMT.csv with 3770 rows
✅ Saved WRB.csv with 3770 rows
✅ Saved WST.csv with 3770 rows
✅ Saved WTW.csv with 3770 rows
✅ Saved WY.csv with 3770 rows
✅ Saved WYNN.csv with 3770 rows
✅ Saved XEL.csv with 3770 rows
✅ Saved XOM.csv with 3770 rows
✅ Saved XYL.csv with 3374 rows
✅ Saved YUM.csv with 3770 rows
✅ Saved ZBH.csv with 3770 rows
✅ Saved ZBRA.csv with 3770 rows
✅ Saved ZTS.csv with 3048 rows
🎯 All stock CSVs are now Fin-GAN-ready!

In [11]:
# === ETFS ===

# Load the ETF-wide CSV
etf_data = pd.read_csv('etf_data.csv')
etf_data['Date'] = pd.to_datetime(etf_data['Date'])

# Output folder
output_folder = 'Fin-GAN-main/datasets'
os.makedirs(output_folder, exist_ok=True)

# Extract all unique ETF tickers from column names
etf_tickers = set()
for col in etf_data.columns:
    if col.endswith('.close'):
        etf_tickers.add(col.replace('.close', ''))

print(f"📈 Found {len(etf_tickers)} ETF tickers")

# Generate per-ETF files
for ticker in sorted(etf_tickers):
    close_col = f'{ticker}.close'
    open_col = f'{ticker}.open'
    
    if close_col in etf_data.columns and open_col in etf_data.columns:
        df = pd.DataFrame({
            'date': etf_data['Date'],
            'AdjClose': etf_data[close_col],
            'AdjOpen': etf_data[open_col]
        })

        df.dropna(inplace=True)
        df = df.sort_values('date').reset_index(drop=True)

        filename = os.path.join(output_folder, f'{ticker}.csv')
        df.to_csv(filename, index=False)
        print(f"✅ Saved {filename} with {len(df)} rows")
    else:
        print(f"⚠️ Missing data for {ticker}, skipping...")

print("🎯 All ETF files saved in Fin-GAN-main/datasets")

📈 Found 11 ETF tickers
✅ Saved Fin-GAN-main/datasets/XLB.csv with 3770 rows
✅ Saved Fin-GAN-main/datasets/XLC.csv with 1694 rows
✅ Saved Fin-GAN-main/datasets/XLE.csv with 3770 rows
✅ Saved Fin-GAN-main/datasets/XLF.csv with 3770 rows
✅ Saved Fin-GAN-main/datasets/XLI.csv with 3770 rows
✅ Saved Fin-GAN-main/datasets/XLK.csv with 3770 rows
✅ Saved Fin-GAN-main/datasets/XLP.csv with 3770 rows
✅ Saved Fin-GAN-main/datasets/XLRE.csv with 2372 rows
✅ Saved Fin-GAN-main/datasets/XLU.csv with 3770 rows
✅ Saved Fin-GAN-main/datasets/XLV.csv with 3770 rows
✅ Saved Fin-GAN-main/datasets/XLY.csv with 3770 rows
🎯 All ETF files saved in Fin-GAN-main/datasets

/var/folders/k1/p_xw0_4x4zd812685rsx20380000gn/T/ipykernel_36895/1500372166.py:5: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  etf_data['Date'] = pd.to_datetime(etf_data['Date'])

In [1]:
# ALIGNED FILES TO AVOID MISMATCH WITH NAN

import pandas as pd
import os

# === CONFIG ===
stock_data_file = 'stock_data.csv'
etf_data_file = 'etf_data.csv'
mapping_file = 'Fin-GAN-main/datasets/stocks-etfs-list.csv'
output_path = 'Fin-GAN-main/datasets'

# === SETUP ===
os.makedirs(output_path, exist_ok=True)

stock_data = pd.read_csv(stock_data_file)
etf_data = pd.read_csv(etf_data_file)
mapping_df = pd.read_csv(mapping_file)

stock_data['Date'] = pd.to_datetime(stock_data['Date'])
etf_data['Date'] = pd.to_datetime(etf_data['Date'])

stock_data.set_index('Date', inplace=False)
etf_data.set_index('Date', inplace=False)

# === MAIN LOOP: Process each stock and its ETF ===
for _, row in mapping_df.iterrows():
    stock = row['ticker_x']
    etf = row['SectorTicker']

    stock_close = f"{stock}.close"
    stock_open = f"{stock}.open"
    etf_close = f"{etf}.close"
    etf_open = f"{etf}.open"

    # Check required columns
    if all(col in stock_data.columns for col in [stock_close, stock_open]) and \
       all(col in etf_data.columns for col in [etf_close, etf_open]):

        # Extract data
        s_df = stock_data[['Date', stock_close, stock_open]].copy()
        s_df.columns = ['date', 'AdjClose_stock', 'AdjOpen_stock']

        e_df = etf_data[['Date', etf_close, etf_open]].copy()
        e_df.columns = ['date', 'AdjClose_etf', 'AdjOpen_etf']

        # Merge and align
        merged = pd.merge(s_df, e_df, on='date', how='inner')
        merged.dropna(inplace=True)

        # === Save aligned stock ===
        s_out = merged[['date', 'AdjClose_stock', 'AdjOpen_stock']].rename(
            columns={'AdjClose_stock': 'AdjClose', 'AdjOpen_stock': 'AdjOpen'}
        )
        s_out.to_csv(os.path.join(output_path, f"{stock}.csv"), index=False)

        # === Save aligned ETF ===
        e_out = merged[['date', 'AdjClose_etf', 'AdjOpen_etf']].rename(
            columns={'AdjClose_etf': 'AdjClose', 'AdjOpen_etf': 'AdjOpen'}
        )
        e_out.to_csv(os.path.join(output_path, f"{etf}.csv"), index=False)

        print(f"✅ Saved aligned: {stock}.csv and {etf}.csv")

    else:
        print(f"⚠️ Skipped {stock} or {etf} — missing columns")

print("🎯 All files are clean, aligned, and FinGAN-ready!")

/var/folders/k1/p_xw0_4x4zd812685rsx20380000gn/T/ipykernel_39775/1034287269.py:19: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  stock_data['Date'] = pd.to_datetime(stock_data['Date'])
/var/folders/k1/p_xw0_4x4zd812685rsx20380000gn/T/ipykernel_39775/1034287269.py:20: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  etf_data['Date'] = pd.to_datetime(etf_data['Date'])

✅ Saved aligned: MMM.csv and XLI.csv
✅ Saved aligned: AOS.csv and XLI.csv
✅ Saved aligned: ABT.csv and XLV.csv
✅ Saved aligned: ABBV.csv and XLV.csv
✅ Saved aligned: ACN.csv and XLK.csv
✅ Saved aligned: ADBE.csv and XLK.csv
✅ Saved aligned: AMD.csv and XLK.csv
✅ Saved aligned: AES.csv and XLU.csv
✅ Saved aligned: AFL.csv and XLF.csv
✅ Saved aligned: A.csv and XLV.csv
✅ Saved aligned: APD.csv and XLB.csv
✅ Saved aligned: ABNB.csv and XLY.csv
✅ Saved aligned: AKAM.csv and XLK.csv
✅ Saved aligned: ALB.csv and XLB.csv
✅ Saved aligned: ARE.csv and XLRE.csv
✅ Saved aligned: ALGN.csv and XLV.csv
✅ Saved aligned: ALLE.csv and XLI.csv
✅ Saved aligned: LNT.csv and XLU.csv
✅ Saved aligned: ALL.csv and XLF.csv
✅ Saved aligned: GOOGL.csv and XLC.csv
✅ Saved aligned: GOOG.csv and XLC.csv
✅ Saved aligned: MO.csv and XLP.csv
✅ Saved aligned: AMZN.csv and XLY.csv
✅ Saved aligned: AMCR.csv and XLB.csv
✅ Saved aligned: AEE.csv and XLU.csv
✅ Saved aligned: AEP.csv and XLU.csv
✅ Saved aligned: AXP.csv and XLF.csv
✅ Saved aligned: AIG.csv and XLF.csv
✅ Saved aligned: AMT.csv and XLRE.csv
✅ Saved aligned: AWK.csv and XLU.csv
✅ Saved aligned: AMP.csv and XLF.csv
✅ Saved aligned: AME.csv and XLI.csv
✅ Saved aligned: AMGN.csv and XLV.csv
✅ Saved aligned: APH.csv and XLK.csv
✅ Saved aligned: ADI.csv and XLK.csv
✅ Saved aligned: ANSS.csv and XLK.csv
✅ Saved aligned: AON.csv and XLF.csv
✅ Saved aligned: APA.csv and XLE.csv
✅ Saved aligned: APO.csv and XLF.csv
✅ Saved aligned: AAPL.csv and XLK.csv
✅ Saved aligned: AMAT.csv and XLK.csv
✅ Saved aligned: APTV.csv and XLY.csv
✅ Saved aligned: ACGL.csv and XLF.csv
✅ Saved aligned: ADM.csv and XLP.csv
✅ Saved aligned: ANET.csv and XLK.csv
✅ Saved aligned: AJG.csv and XLF.csv
✅ Saved aligned: AIZ.csv and XLF.csv
✅ Saved aligned: T.csv and XLC.csv
✅ Saved aligned: ATO.csv and XLU.csv
✅ Saved aligned: ADSK.csv and XLK.csv
✅ Saved aligned: ADP.csv and XLI.csv
✅ Saved aligned: AZO.csv and XLY.csv
✅ Saved aligned: AVB.csv and XLRE.csv
✅ Saved aligned: AVY.csv and XLB.csv
✅ Saved aligned: AXON.csv and XLI.csv
✅ Saved aligned: BKR.csv and XLE.csv
✅ Saved aligned: BALL.csv and XLB.csv
✅ Saved aligned: BAC.csv and XLF.csv
✅ Saved aligned: BAX.csv and XLV.csv
✅ Saved aligned: BDX.csv and XLV.csv
✅ Saved aligned: BRK-B.csv and XLF.csv
✅ Saved aligned: BBY.csv and XLY.csv
✅ Saved aligned: TECH.csv and XLV.csv
✅ Saved aligned: BIIB.csv and XLV.csv
✅ Saved aligned: BLK.csv and XLF.csv
✅ Saved aligned: BX.csv and XLF.csv
✅ Saved aligned: BK.csv and XLF.csv
✅ Saved aligned: BA.csv and XLI.csv
✅ Saved aligned: BKNG.csv and XLY.csv
✅ Saved aligned: BWA.csv and XLY.csv
✅ Saved aligned: BSX.csv and XLV.csv
✅ Saved aligned: BMY.csv and XLV.csv
✅ Saved aligned: AVGO.csv and XLK.csv
✅ Saved aligned: BR.csv and XLI.csv
✅ Saved aligned: BRO.csv and XLF.csv
✅ Saved aligned: BF-B.csv and XLP.csv
✅ Saved aligned: BLDR.csv and XLI.csv
✅ Saved aligned: BG.csv and XLP.csv
✅ Saved aligned: BXP.csv and XLRE.csv
✅ Saved aligned: CHRW.csv and XLI.csv
✅ Saved aligned: CDNS.csv and XLK.csv
✅ Saved aligned: CZR.csv and XLY.csv
✅ Saved aligned: CPT.csv and XLRE.csv
✅ Saved aligned: CPB.csv and XLP.csv
✅ Saved aligned: COF.csv and XLF.csv
✅ Saved aligned: CAH.csv and XLV.csv
✅ Saved aligned: KMX.csv and XLY.csv
✅ Saved aligned: CCL.csv and XLY.csv
✅ Saved aligned: CARR.csv and XLI.csv
✅ Saved aligned: CAT.csv and XLI.csv
✅ Saved aligned: CBOE.csv and XLF.csv
✅ Saved aligned: CBRE.csv and XLRE.csv
✅ Saved aligned: CDW.csv and XLK.csv
✅ Saved aligned: CE.csv and XLB.csv
✅ Saved aligned: COR.csv and XLV.csv
✅ Saved aligned: CNC.csv and XLV.csv
✅ Saved aligned: CNP.csv and XLU.csv
✅ Saved aligned: CF.csv and XLB.csv
✅ Saved aligned: CRL.csv and XLV.csv
✅ Saved aligned: SCHW.csv and XLF.csv
✅ Saved aligned: CHTR.csv and XLC.csv
✅ Saved aligned: CVX.csv and XLE.csv
✅ Saved aligned: CMG.csv and XLY.csv
✅ Saved aligned: CB.csv and XLF.csv
✅ Saved aligned: CHD.csv and XLP.csv
✅ Saved aligned: CI.csv and XLV.csv
✅ Saved aligned: CINF.csv and XLF.csv
✅ Saved aligned: CTAS.csv and XLI.csv
✅ Saved aligned: CSCO.csv and XLK.csv
✅ Saved aligned: C.csv and XLF.csv
✅ Saved aligned: CFG.csv and XLF.csv
✅ Saved aligned: CLX.csv and XLP.csv
✅ Saved aligned: CME.csv and XLF.csv
✅ Saved aligned: CMS.csv and XLU.csv
✅ Saved aligned: KO.csv and XLP.csv
✅ Saved aligned: CTSH.csv and XLK.csv
✅ Saved aligned: CL.csv and XLP.csv
✅ Saved aligned: CMCSA.csv and XLC.csv
✅ Saved aligned: CAG.csv and XLP.csv
✅ Saved aligned: COP.csv and XLE.csv
✅ Saved aligned: ED.csv and XLU.csv
✅ Saved aligned: STZ.csv and XLP.csv
✅ Saved aligned: CEG.csv and XLU.csv
✅ Saved aligned: COO.csv and XLV.csv
✅ Saved aligned: CPRT.csv and XLI.csv
✅ Saved aligned: GLW.csv and XLK.csv
✅ Saved aligned: CPAY.csv and XLF.csv
✅ Saved aligned: CTVA.csv and XLB.csv
✅ Saved aligned: CSGP.csv and XLRE.csv
✅ Saved aligned: COST.csv and XLP.csv
✅ Saved aligned: CTRA.csv and XLE.csv
✅ Saved aligned: CRWD.csv and XLK.csv
✅ Saved aligned: CCI.csv and XLRE.csv
✅ Saved aligned: CSX.csv and XLI.csv
✅ Saved aligned: CMI.csv and XLI.csv
✅ Saved aligned: CVS.csv and XLV.csv
✅ Saved aligned: DHR.csv and XLV.csv
✅ Saved aligned: DRI.csv and XLY.csv
✅ Saved aligned: DVA.csv and XLV.csv
✅ Saved aligned: DAY.csv and XLI.csv
✅ Saved aligned: DECK.csv and XLY.csv
✅ Saved aligned: DE.csv and XLI.csv
✅ Saved aligned: DELL.csv and XLK.csv
✅ Saved aligned: DAL.csv and XLI.csv
✅ Saved aligned: DVN.csv and XLE.csv
✅ Saved aligned: DXCM.csv and XLV.csv
✅ Saved aligned: FANG.csv and XLE.csv
✅ Saved aligned: DLR.csv and XLRE.csv
✅ Saved aligned: DFS.csv and XLF.csv
✅ Saved aligned: DG.csv and XLP.csv
✅ Saved aligned: DLTR.csv and XLP.csv
✅ Saved aligned: D.csv and XLU.csv
✅ Saved aligned: DPZ.csv and XLY.csv
✅ Saved aligned: DOV.csv and XLI.csv
✅ Saved aligned: DOW.csv and XLB.csv
✅ Saved aligned: DHI.csv and XLY.csv
✅ Saved aligned: DTE.csv and XLU.csv
✅ Saved aligned: DUK.csv and XLU.csv
✅ Saved aligned: DD.csv and XLB.csv
✅ Saved aligned: EMN.csv and XLB.csv
✅ Saved aligned: ETN.csv and XLI.csv
✅ Saved aligned: EBAY.csv and XLY.csv
✅ Saved aligned: ECL.csv and XLB.csv
✅ Saved aligned: EIX.csv and XLU.csv
✅ Saved aligned: EW.csv and XLV.csv
✅ Saved aligned: EA.csv and XLC.csv
✅ Saved aligned: ELV.csv and XLV.csv
✅ Saved aligned: EMR.csv and XLI.csv
✅ Saved aligned: ENPH.csv and XLK.csv
✅ Saved aligned: ETR.csv and XLU.csv
✅ Saved aligned: EOG.csv and XLE.csv
✅ Saved aligned: EPAM.csv and XLK.csv
✅ Saved aligned: EQT.csv and XLE.csv
✅ Saved aligned: EFX.csv and XLI.csv
✅ Saved aligned: EQIX.csv and XLRE.csv
✅ Saved aligned: EQR.csv and XLRE.csv
✅ Saved aligned: ERIE.csv and XLF.csv
✅ Saved aligned: ESS.csv and XLRE.csv
✅ Saved aligned: EL.csv and XLP.csv
✅ Saved aligned: EG.csv and XLF.csv
✅ Saved aligned: EVRG.csv and XLU.csv
✅ Saved aligned: ES.csv and XLU.csv
✅ Saved aligned: EXC.csv and XLU.csv
✅ Saved aligned: EXPE.csv and XLY.csv
✅ Saved aligned: EXPD.csv and XLI.csv
✅ Saved aligned: EXR.csv and XLRE.csv
✅ Saved aligned: XOM.csv and XLE.csv
✅ Saved aligned: FFIV.csv and XLK.csv
✅ Saved aligned: FDS.csv and XLF.csv
✅ Saved aligned: FICO.csv and XLK.csv
✅ Saved aligned: FAST.csv and XLI.csv
✅ Saved aligned: FRT.csv and XLRE.csv
✅ Saved aligned: FDX.csv and XLI.csv
✅ Saved aligned: FIS.csv and XLF.csv
✅ Saved aligned: FITB.csv and XLF.csv
✅ Saved aligned: FSLR.csv and XLK.csv
✅ Saved aligned: FE.csv and XLU.csv
✅ Saved aligned: FI.csv and XLF.csv
✅ Saved aligned: FMC.csv and XLB.csv
✅ Saved aligned: F.csv and XLY.csv
✅ Saved aligned: FTNT.csv and XLK.csv
✅ Saved aligned: FTV.csv and XLI.csv
✅ Saved aligned: FOXA.csv and XLC.csv
✅ Saved aligned: FOX.csv and XLC.csv
✅ Saved aligned: BEN.csv and XLF.csv
✅ Saved aligned: FCX.csv and XLB.csv
✅ Saved aligned: GRMN.csv and XLY.csv
✅ Saved aligned: IT.csv and XLK.csv
✅ Saved aligned: GE.csv and XLI.csv
✅ Saved aligned: GEHC.csv and XLV.csv
✅ Saved aligned: GEV.csv and XLI.csv
✅ Saved aligned: GEN.csv and XLK.csv
✅ Saved aligned: GNRC.csv and XLI.csv
✅ Saved aligned: GD.csv and XLI.csv
✅ Saved aligned: GIS.csv and XLP.csv
✅ Saved aligned: GM.csv and XLY.csv
✅ Saved aligned: GPC.csv and XLY.csv
✅ Saved aligned: GILD.csv and XLV.csv
✅ Saved aligned: GPN.csv and XLF.csv
✅ Saved aligned: GL.csv and XLF.csv
✅ Saved aligned: GDDY.csv and XLK.csv
✅ Saved aligned: GS.csv and XLF.csv
✅ Saved aligned: HAL.csv and XLE.csv
✅ Saved aligned: HIG.csv and XLF.csv
✅ Saved aligned: HAS.csv and XLY.csv
✅ Saved aligned: HCA.csv and XLV.csv
✅ Saved aligned: DOC.csv and XLRE.csv
✅ Saved aligned: HSIC.csv and XLV.csv
✅ Saved aligned: HSY.csv and XLP.csv
✅ Saved aligned: HES.csv and XLE.csv
✅ Saved aligned: HPE.csv and XLK.csv
✅ Saved aligned: HLT.csv and XLY.csv
✅ Saved aligned: HOLX.csv and XLV.csv
✅ Saved aligned: HD.csv and XLY.csv
✅ Saved aligned: HON.csv and XLI.csv
✅ Saved aligned: HRL.csv and XLP.csv
✅ Saved aligned: HST.csv and XLRE.csv
✅ Saved aligned: HWM.csv and XLI.csv
✅ Saved aligned: HPQ.csv and XLK.csv
✅ Saved aligned: HUBB.csv and XLI.csv
✅ Saved aligned: HUM.csv and XLV.csv
✅ Saved aligned: HBAN.csv and XLF.csv
✅ Saved aligned: HII.csv and XLI.csv
✅ Saved aligned: IBM.csv and XLK.csv
✅ Saved aligned: IEX.csv and XLI.csv
✅ Saved aligned: IDXX.csv and XLV.csv
✅ Saved aligned: ITW.csv and XLI.csv
✅ Saved aligned: INCY.csv and XLV.csv
✅ Saved aligned: IR.csv and XLI.csv
✅ Saved aligned: PODD.csv and XLV.csv
✅ Saved aligned: INTC.csv and XLK.csv
✅ Saved aligned: ICE.csv and XLF.csv
✅ Saved aligned: IFF.csv and XLB.csv
✅ Saved aligned: IP.csv and XLB.csv
✅ Saved aligned: IPG.csv and XLC.csv
✅ Saved aligned: INTU.csv and XLK.csv
✅ Saved aligned: ISRG.csv and XLV.csv
✅ Saved aligned: IVZ.csv and XLF.csv
✅ Saved aligned: INVH.csv and XLRE.csv
✅ Saved aligned: IQV.csv and XLV.csv
✅ Saved aligned: IRM.csv and XLRE.csv
✅ Saved aligned: JBHT.csv and XLI.csv
✅ Saved aligned: JBL.csv and XLK.csv
✅ Saved aligned: JKHY.csv and XLF.csv
✅ Saved aligned: J.csv and XLI.csv
✅ Saved aligned: JNJ.csv and XLV.csv
✅ Saved aligned: JCI.csv and XLI.csv
✅ Saved aligned: JPM.csv and XLF.csv
✅ Saved aligned: JNPR.csv and XLK.csv
✅ Saved aligned: K.csv and XLP.csv
✅ Saved aligned: KVUE.csv and XLP.csv
✅ Saved aligned: KDP.csv and XLP.csv
✅ Saved aligned: KEY.csv and XLF.csv
✅ Saved aligned: KEYS.csv and XLK.csv
✅ Saved aligned: KMB.csv and XLP.csv
✅ Saved aligned: KIM.csv and XLRE.csv
✅ Saved aligned: KMI.csv and XLE.csv
✅ Saved aligned: KKR.csv and XLF.csv
✅ Saved aligned: KLAC.csv and XLK.csv
✅ Saved aligned: KHC.csv and XLP.csv
✅ Saved aligned: KR.csv and XLP.csv
✅ Saved aligned: LHX.csv and XLI.csv
✅ Saved aligned: LH.csv and XLV.csv
✅ Saved aligned: LRCX.csv and XLK.csv
✅ Saved aligned: LW.csv and XLP.csv
✅ Saved aligned: LVS.csv and XLY.csv
✅ Saved aligned: LDOS.csv and XLI.csv
✅ Saved aligned: LEN.csv and XLY.csv
✅ Saved aligned: LII.csv and XLI.csv
✅ Saved aligned: LLY.csv and XLV.csv
✅ Saved aligned: LIN.csv and XLB.csv
✅ Saved aligned: LYV.csv and XLC.csv
✅ Saved aligned: LKQ.csv and XLY.csv
✅ Saved aligned: LMT.csv and XLI.csv
✅ Saved aligned: L.csv and XLF.csv
✅ Saved aligned: LOW.csv and XLY.csv
✅ Saved aligned: LULU.csv and XLY.csv
✅ Saved aligned: LYB.csv and XLB.csv
✅ Saved aligned: MTB.csv and XLF.csv
✅ Saved aligned: MPC.csv and XLE.csv
✅ Saved aligned: MKTX.csv and XLF.csv
✅ Saved aligned: MAR.csv and XLY.csv
✅ Saved aligned: MMC.csv and XLF.csv
✅ Saved aligned: MLM.csv and XLB.csv
✅ Saved aligned: MAS.csv and XLI.csv
✅ Saved aligned: MA.csv and XLF.csv
✅ Saved aligned: MTCH.csv and XLC.csv
✅ Saved aligned: MKC.csv and XLP.csv
✅ Saved aligned: MCD.csv and XLY.csv
✅ Saved aligned: MCK.csv and XLV.csv
✅ Saved aligned: MDT.csv and XLV.csv
✅ Saved aligned: MRK.csv and XLV.csv
✅ Saved aligned: META.csv and XLC.csv
✅ Saved aligned: MET.csv and XLF.csv
✅ Saved aligned: MTD.csv and XLV.csv
✅ Saved aligned: MGM.csv and XLY.csv
✅ Saved aligned: MCHP.csv and XLK.csv
✅ Saved aligned: MU.csv and XLK.csv
✅ Saved aligned: MSFT.csv and XLK.csv
✅ Saved aligned: MAA.csv and XLRE.csv
✅ Saved aligned: MRNA.csv and XLV.csv
✅ Saved aligned: MHK.csv and XLY.csv
✅ Saved aligned: MOH.csv and XLV.csv
✅ Saved aligned: TAP.csv and XLP.csv
✅ Saved aligned: MDLZ.csv and XLP.csv
✅ Saved aligned: MPWR.csv and XLK.csv
✅ Saved aligned: MNST.csv and XLP.csv
✅ Saved aligned: MCO.csv and XLF.csv
✅ Saved aligned: MS.csv and XLF.csv
✅ Saved aligned: MOS.csv and XLB.csv
✅ Saved aligned: MSI.csv and XLK.csv
✅ Saved aligned: MSCI.csv and XLF.csv
✅ Saved aligned: NDAQ.csv and XLF.csv
✅ Saved aligned: NTAP.csv and XLK.csv
✅ Saved aligned: NFLX.csv and XLC.csv
✅ Saved aligned: NEM.csv and XLB.csv
✅ Saved aligned: NWSA.csv and XLC.csv
✅ Saved aligned: NWS.csv and XLC.csv
✅ Saved aligned: NEE.csv and XLU.csv
✅ Saved aligned: NKE.csv and XLY.csv
✅ Saved aligned: NI.csv and XLU.csv
✅ Saved aligned: NDSN.csv and XLI.csv
✅ Saved aligned: NSC.csv and XLI.csv
✅ Saved aligned: NTRS.csv and XLF.csv
✅ Saved aligned: NOC.csv and XLI.csv
✅ Saved aligned: NCLH.csv and XLY.csv
✅ Saved aligned: NRG.csv and XLU.csv
✅ Saved aligned: NUE.csv and XLB.csv
✅ Saved aligned: NVDA.csv and XLK.csv
✅ Saved aligned: NVR.csv and XLY.csv
✅ Saved aligned: NXPI.csv and XLK.csv
✅ Saved aligned: ORLY.csv and XLY.csv
✅ Saved aligned: OXY.csv and XLE.csv
✅ Saved aligned: ODFL.csv and XLI.csv
✅ Saved aligned: OMC.csv and XLC.csv
✅ Saved aligned: ON.csv and XLK.csv
✅ Saved aligned: OKE.csv and XLE.csv
✅ Saved aligned: ORCL.csv and XLK.csv
✅ Saved aligned: OTIS.csv and XLI.csv
✅ Saved aligned: PCAR.csv and XLI.csv
✅ Saved aligned: PKG.csv and XLB.csv
✅ Saved aligned: PLTR.csv and XLK.csv
✅ Saved aligned: PANW.csv and XLK.csv
✅ Saved aligned: PARA.csv and XLC.csv
✅ Saved aligned: PH.csv and XLI.csv
✅ Saved aligned: PAYX.csv and XLI.csv
✅ Saved aligned: PAYC.csv and XLI.csv
✅ Saved aligned: PYPL.csv and XLF.csv
✅ Saved aligned: PNR.csv and XLI.csv
✅ Saved aligned: PEP.csv and XLP.csv
✅ Saved aligned: PFE.csv and XLV.csv
✅ Saved aligned: PCG.csv and XLU.csv
✅ Saved aligned: PM.csv and XLP.csv
✅ Saved aligned: PSX.csv and XLE.csv
✅ Saved aligned: PNW.csv and XLU.csv
✅ Saved aligned: PNC.csv and XLF.csv
✅ Saved aligned: POOL.csv and XLY.csv
✅ Saved aligned: PPG.csv and XLB.csv
✅ Saved aligned: PPL.csv and XLU.csv
✅ Saved aligned: PFG.csv and XLF.csv
✅ Saved aligned: PG.csv and XLP.csv
✅ Saved aligned: PGR.csv and XLF.csv
✅ Saved aligned: PLD.csv and XLRE.csv
✅ Saved aligned: PRU.csv and XLF.csv
✅ Saved aligned: PEG.csv and XLU.csv
✅ Saved aligned: PTC.csv and XLK.csv
✅ Saved aligned: PSA.csv and XLRE.csv
✅ Saved aligned: PHM.csv and XLY.csv
✅ Saved aligned: PWR.csv and XLI.csv
✅ Saved aligned: QCOM.csv and XLK.csv
✅ Saved aligned: DGX.csv and XLV.csv
✅ Saved aligned: RL.csv and XLY.csv
✅ Saved aligned: RJF.csv and XLF.csv
✅ Saved aligned: RTX.csv and XLI.csv
✅ Saved aligned: O.csv and XLRE.csv
✅ Saved aligned: REG.csv and XLRE.csv
✅ Saved aligned: REGN.csv and XLV.csv
✅ Saved aligned: RF.csv and XLF.csv
✅ Saved aligned: RSG.csv and XLI.csv
✅ Saved aligned: RMD.csv and XLV.csv
✅ Saved aligned: RVTY.csv and XLV.csv
✅ Saved aligned: ROK.csv and XLI.csv
✅ Saved aligned: ROL.csv and XLI.csv
✅ Saved aligned: ROP.csv and XLK.csv
✅ Saved aligned: ROST.csv and XLY.csv
✅ Saved aligned: RCL.csv and XLY.csv
✅ Saved aligned: SPGI.csv and XLF.csv
✅ Saved aligned: CRM.csv and XLK.csv
✅ Saved aligned: SBAC.csv and XLRE.csv
✅ Saved aligned: SLB.csv and XLE.csv
✅ Saved aligned: STX.csv and XLK.csv
✅ Saved aligned: SRE.csv and XLU.csv
✅ Saved aligned: NOW.csv and XLK.csv
✅ Saved aligned: SHW.csv and XLB.csv
✅ Saved aligned: SPG.csv and XLRE.csv
✅ Saved aligned: SWKS.csv and XLK.csv
✅ Saved aligned: SJM.csv and XLP.csv
✅ Saved aligned: SW.csv and XLB.csv
✅ Saved aligned: SNA.csv and XLI.csv
✅ Saved aligned: SOLV.csv and XLV.csv
✅ Saved aligned: SO.csv and XLU.csv
✅ Saved aligned: LUV.csv and XLI.csv
✅ Saved aligned: SWK.csv and XLI.csv
✅ Saved aligned: SBUX.csv and XLY.csv
✅ Saved aligned: STT.csv and XLF.csv
✅ Saved aligned: STLD.csv and XLB.csv
✅ Saved aligned: STE.csv and XLV.csv
✅ Saved aligned: SYK.csv and XLV.csv
✅ Saved aligned: SMCI.csv and XLK.csv
✅ Saved aligned: SYF.csv and XLF.csv
✅ Saved aligned: SNPS.csv and XLK.csv
✅ Saved aligned: SYY.csv and XLP.csv
✅ Saved aligned: TMUS.csv and XLC.csv
✅ Saved aligned: TROW.csv and XLF.csv
✅ Saved aligned: TTWO.csv and XLC.csv
✅ Saved aligned: TPR.csv and XLY.csv
✅ Saved aligned: TRGP.csv and XLE.csv
✅ Saved aligned: TGT.csv and XLP.csv
✅ Saved aligned: TEL.csv and XLK.csv
✅ Saved aligned: TDY.csv and XLK.csv
✅ Saved aligned: TFX.csv and XLV.csv
✅ Saved aligned: TER.csv and XLK.csv
✅ Saved aligned: TSLA.csv and XLY.csv
✅ Saved aligned: TXN.csv and XLK.csv
✅ Saved aligned: TPL.csv and XLE.csv
✅ Saved aligned: TXT.csv and XLI.csv
✅ Saved aligned: TMO.csv and XLV.csv
✅ Saved aligned: TJX.csv and XLY.csv
✅ Saved aligned: TSCO.csv and XLY.csv
✅ Saved aligned: TT.csv and XLI.csv
✅ Saved aligned: TDG.csv and XLI.csv
✅ Saved aligned: TRV.csv and XLF.csv
✅ Saved aligned: TRMB.csv and XLK.csv
✅ Saved aligned: TFC.csv and XLF.csv
✅ Saved aligned: TYL.csv and XLK.csv
✅ Saved aligned: TSN.csv and XLP.csv
✅ Saved aligned: USB.csv and XLF.csv
✅ Saved aligned: UBER.csv and XLI.csv
✅ Saved aligned: UDR.csv and XLRE.csv
✅ Saved aligned: ULTA.csv and XLY.csv
✅ Saved aligned: UNP.csv and XLI.csv
✅ Saved aligned: UAL.csv and XLI.csv
✅ Saved aligned: UPS.csv and XLI.csv
✅ Saved aligned: URI.csv and XLI.csv
✅ Saved aligned: UNH.csv and XLV.csv
✅ Saved aligned: UHS.csv and XLV.csv
✅ Saved aligned: VLO.csv and XLE.csv
✅ Saved aligned: VTR.csv and XLRE.csv
✅ Saved aligned: VLTO.csv and XLI.csv
✅ Saved aligned: VRSN.csv and XLK.csv
✅ Saved aligned: VRSK.csv and XLI.csv
✅ Saved aligned: VZ.csv and XLC.csv
✅ Saved aligned: VRTX.csv and XLV.csv
✅ Saved aligned: VTRS.csv and XLV.csv
✅ Saved aligned: VICI.csv and XLRE.csv
✅ Saved aligned: V.csv and XLF.csv
✅ Saved aligned: VST.csv and XLU.csv
✅ Saved aligned: VMC.csv and XLB.csv
✅ Saved aligned: WRB.csv and XLF.csv
✅ Saved aligned: GWW.csv and XLI.csv
✅ Saved aligned: WAB.csv and XLI.csv
✅ Saved aligned: WBA.csv and XLP.csv
✅ Saved aligned: WMT.csv and XLP.csv
✅ Saved aligned: DIS.csv and XLC.csv
✅ Saved aligned: WBD.csv and XLC.csv
✅ Saved aligned: WM.csv and XLI.csv
✅ Saved aligned: WAT.csv and XLV.csv
✅ Saved aligned: WEC.csv and XLU.csv
✅ Saved aligned: WFC.csv and XLF.csv
✅ Saved aligned: WELL.csv and XLRE.csv
✅ Saved aligned: WST.csv and XLV.csv
✅ Saved aligned: WDC.csv and XLK.csv
✅ Saved aligned: WY.csv and XLRE.csv
✅ Saved aligned: WMB.csv and XLE.csv
✅ Saved aligned: WTW.csv and XLF.csv
✅ Saved aligned: WDAY.csv and XLK.csv
✅ Saved aligned: WYNN.csv and XLY.csv
✅ Saved aligned: XEL.csv and XLU.csv
✅ Saved aligned: XYL.csv and XLI.csv
✅ Saved aligned: YUM.csv and XLY.csv
✅ Saved aligned: ZBRA.csv and XLK.csv
✅ Saved aligned: ZBH.csv and XLV.csv
✅ Saved aligned: ZTS.csv and XLV.csv
🎯 All files are clean, aligned, and FinGAN-ready!